---

# EXPLORING DATAFRAMES: INFO & DESCRIBE

---

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Data/retail_2016_2017.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  object
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  object
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 48.3+ MB

In [3]:
df.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [4]:
df.describe()

                 id     store_nbr         sales   onpromotion
count  1.054944e+06  1.054944e+06  1.054944e+06  1.054944e+06
mean   2.473416e+06  2.750000e+01  4.577225e+02  5.937977e+00
std    3.045362e+05  1.558579e+01  1.317155e+03  1.808632e+01
min    1.945944e+06  1.000000e+00  0.000000e+00  0.000000e+00
25%    2.209680e+06  1.400000e+01  2.000000e+00  0.000000e+00
50%    2.473416e+06  2.750000e+01  2.400000e+01  0.000000e+00
75%    2.737151e+06  4.100000e+01  2.620000e+02  3.000000e+00
max    3.000887e+06  5.400000e+01  1.247170e+05  7.410000e+02

In [5]:
df.describe().round()

              id  store_nbr      sales  onpromotion
count  1054944.0  1054944.0  1054944.0    1054944.0
mean   2473416.0       28.0      458.0          6.0
std     304536.0       16.0     1317.0         18.0
min    1945944.0        1.0        0.0          0.0
25%    2209680.0       14.0        2.0          0.0
50%    2473416.0       28.0       24.0          0.0
75%    2737151.0       41.0      262.0          3.0
max    3000887.0       54.0   124717.0        741.0

In [6]:
df.describe(include='all').round()

               id        date  store_nbr      family      sales  onpromotion
count   1054944.0     1054944  1054944.0     1054944  1054944.0    1054944.0
unique        NaN         592        NaN          33        NaN          NaN
top           NaN  2016-01-01        NaN  AUTOMOTIVE        NaN          NaN
freq          NaN        1782        NaN       31968        NaN          NaN
mean    2473416.0         NaN       28.0         NaN      458.0          6.0
std      304536.0         NaN       16.0         NaN     1317.0         18.0
min     1945944.0         NaN        1.0         NaN        0.0          0.0
25%     2209680.0         NaN       14.0         NaN        2.0          0.0
50%     2473416.0         NaN       28.0         NaN       24.0          0.0
75%     2737151.0         NaN       41.0         NaN      262.0          3.0
max     3000887.0         NaN       54.0         NaN   124717.0        741.0

---

# ASSIGNMENT: EXPLORING DATAFRAMES 

---

In [7]:
transactions = pd.read_csv('Data/transactions.csv')
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [8]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  object
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.9+ MB

In [9]:
# Check missing values
transactions.isna().sum()

date            0
store_nbr       0
transactions    0
dtype: int64

In [10]:
transactions['date'].unique()

array(['2013-01-01', '2013-01-02', '2013-01-03', ..., '2017-08-13',
       '2017-08-14', '2017-08-15'], shape=(1682,), dtype=object)

In [11]:
transactions.describe(include='all')

              date     store_nbr  transactions
count        83488  83488.000000  83488.000000
unique        1682           NaN           NaN
top     2017-07-15           NaN           NaN
freq            54           NaN           NaN
mean           NaN     26.939237   1694.602158
std            NaN     15.608204    963.286644
min            NaN      1.000000      5.000000
25%            NaN     13.000000   1046.000000
50%            NaN     27.000000   1393.000000
75%            NaN     40.000000   2079.000000
max            NaN     54.000000   8359.000000