---

# ACCESSING DATAFRAME DATA WITH `.iloc[]` and `.loc[]`

---

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Data/retail_2016_2017.csv')
df.iloc[:3, :]

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0

In [3]:
df.iloc[:, 1:4]

               date  store_nbr                      family
0        2016-01-01          1                  AUTOMOTIVE
1        2016-01-01          1                   BABY CARE
2        2016-01-01          1                      BEAUTY
3        2016-01-01          1                   BEVERAGES
4        2016-01-01          1                       BOOKS
...             ...        ...                         ...
1054939  2017-08-15          9                     POULTRY
1054940  2017-08-15          9              PREPARED FOODS
1054941  2017-08-15          9                     PRODUCE
1054942  2017-08-15          9  SCHOOL AND OFFICE SUPPLIES
1054943  2017-08-15          9                     SEAFOOD

[1054944 rows x 3 columns]

In [4]:
df.loc[:, 'date':'sales']

               date  store_nbr                      family     sales
0        2016-01-01          1                  AUTOMOTIVE     0.000
1        2016-01-01          1                   BABY CARE     0.000
2        2016-01-01          1                      BEAUTY     0.000
3        2016-01-01          1                   BEVERAGES     0.000
4        2016-01-01          1                       BOOKS     0.000
...             ...        ...                         ...       ...
1054939  2017-08-15          9                     POULTRY   438.133
1054940  2017-08-15          9              PREPARED FOODS   154.553
1054941  2017-08-15          9                     PRODUCE  2419.729
1054942  2017-08-15          9  SCHOOL AND OFFICE SUPPLIES   121.000
1054943  2017-08-15          9                     SEAFOOD    16.000

[1054944 rows x 4 columns]

In [5]:
df.loc[:, ['date', 'sales']]

               date     sales
0        2016-01-01     0.000
1        2016-01-01     0.000
2        2016-01-01     0.000
3        2016-01-01     0.000
4        2016-01-01     0.000
...             ...       ...
1054939  2017-08-15   438.133
1054940  2017-08-15   154.553
1054941  2017-08-15  2419.729
1054942  2017-08-15   121.000
1054943  2017-08-15    16.000

[1054944 rows x 2 columns]

<br><br>

---

<br><br>

In [6]:
oil = pd.read_csv('Data/oil.csv')
oil.columns = ['date', 'price']
oil.loc[:3, :]

         date  price
0  2013-01-01    NaN
1  2013-01-02  93.14
2  2013-01-03  92.97
3  2013-01-04  93.12

In [7]:
oil['euro_price'] = oil['price'] * 1.1
oil.head()

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520

In [8]:
oil.iloc[:9, -2:]

   price  euro_price
0    NaN         NaN
1  93.14     102.454
2  92.97     102.267
3  93.12     102.432
4  93.20     102.520
5  93.21     102.531
6  93.08     102.388
7  93.81     103.191
8  93.60     102.960

---

In [9]:
oil.loc[:5, ['date', 'euro_price']]

         date  euro_price
0  2013-01-01         NaN
1  2013-01-02     102.454
2  2013-01-03     102.267
3  2013-01-04     102.432
4  2013-01-07     102.520
5  2013-01-08     102.531

---

# ASSIGNMENT: ACCESSING DATA

---

In [10]:
df = pd.read_csv('Data/transactions.csv')
df

             date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83488 rows x 3 columns]

In [11]:
df_copy = df.loc[1:, ['store_nbr', 'transactions']]
df_copy

       store_nbr  transactions
1              1          2111
2              2          2358
3              3          3487
4              4          1922
5              5          1903
...          ...           ...
83483         50          2804
83484         51          1573
83485         52          2255
83486         53           932
83487         54           802

[83487 rows x 2 columns]

In [12]:
# unique store numbers
df_copy['store_nbr'].nunique()

54

In [14]:
# total number of transactions in millions
(df.loc[:, 'transactions'].sum())/(1e6)

np.float64(141.478945)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  object
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.9+ MB