---

# DROPPING COLUMNS AND ROWS

---

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Data/retail_2016_2017.csv')
df

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [3]:
df.drop(labels='id', axis=1)

,date,store_nbr,family,sales,onpromotion
0,2016-01-01,1,AUTOMOTIVE,0.000,0
1,2016-01-01,1,BABY CARE,0.000,0
2,2016-01-01,1,BEAUTY,0.000,0
3,2016-01-01,1,BEVERAGES,0.000,0
4,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...
1054939,2017-08-15,9,POULTRY,438.133,0
1054940,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,2017-08-15,9,PRODUCE,2419.729,148
1054942,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,2017-08-15,9,SEAFOOD,16.000,0

In [5]:
drop_df = df.drop(labels=['id', 'onpromotion'], axis=1)
drop_df.head()

         date  store_nbr      family  sales
0  2016-01-01          1  AUTOMOTIVE    0.0
1  2016-01-01          1   BABY CARE    0.0
2  2016-01-01          1      BEAUTY    0.0
3  2016-01-01          1   BEVERAGES    0.0
4  2016-01-01          1       BOOKS    0.0

---

`PRO TIP:` Drop unnecessary columns early in your workflow to save memory and make DataFrames more manageable (*ideally, they shouldn't be imported - more on that later!*)

---

In [7]:
# Dropping Rows with .drop() Method
df

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [11]:
df.drop(labels=[1, 2, 3, 5], axis=0).head()

        id        date  store_nbr       family  sales  onpromotion
0  1945944  2016-01-01          1   AUTOMOTIVE    0.0            0
4  1945948  2016-01-01          1        BOOKS    0.0            0
6  1945950  2016-01-01          1  CELEBRATION    0.0            0
7  1945951  2016-01-01          1     CLEANING    0.0            0
8  1945952  2016-01-01          1        DAIRY    0.0            0

In [12]:
df.drop(labels=range(9), axis=0).head()

         id        date  store_nbr        family  sales  onpromotion
9   1945953  2016-01-01          1          DELI    0.0            0
10  1945954  2016-01-01          1          EGGS    0.0            0
11  1945955  2016-01-01          1  FROZEN FOODS    0.0            0
12  1945956  2016-01-01          1     GROCERY I    0.0            0
13  1945957  2016-01-01          1    GROCERY II    0.0            0

---

You'll tipically drop rows via `slicing` or `filtering`, but it's worth being aware that `.drop()` method can be used as well.

---

In [28]:
oil = pd.read_csv('Data/oil.csv')
oil.columns = ['date', 'price']
oil['euro_price'] = oil['price'] * 1.1
oil

            date  price  euro_price
0     2013-01-01    NaN         NaN
1     2013-01-02  93.14     102.454
2     2013-01-03  92.97     102.267
3     2013-01-04  93.12     102.432
4     2013-01-07  93.20     102.520
...          ...    ...         ...
1213  2017-08-25  47.65      52.415
1214  2017-08-28  46.40      51.040
1215  2017-08-29  46.46      51.106
1216  2017-08-30  45.96      50.556
1217  2017-08-31  47.26      51.986

[1218 rows x 3 columns]

---

`PRO TIP:` It's a good practice to create a new DataFrame when dropping columns from the original DF

---

In [38]:
# Create a new DF to drop columns
oil_euro = oil.drop(labels='price', axis=1)
oil_euro

            date  euro_price
0     2013-01-01         NaN
1     2013-01-02     102.454
2     2013-01-03     102.267
3     2013-01-04     102.432
4     2013-01-07     102.520
...          ...         ...
1213  2017-08-25      52.415
1214  2017-08-28      51.040
1215  2017-08-29      51.106
1216  2017-08-30      50.556
1217  2017-08-31      51.986

[1218 rows x 2 columns]

In [39]:
# Original DF is complete
oil.head()

         date  price  euro_price
0  2013-01-01    NaN         NaN
1  2013-01-02  93.14     102.454
2  2013-01-03  92.97     102.267
3  2013-01-04  93.12     102.432
4  2013-01-07  93.20     102.520

In [40]:
# Now you can work on the new DF. And if you make errors - you can always come back to the original DF
oil_euro.drop(labels=[0, 2, 4, 6, 7, 9, 12], axis=0, inplace=True)
oil_euro

            date  euro_price
1     2013-01-02     102.454
3     2013-01-04     102.432
5     2013-01-08     102.531
8     2013-01-11     102.960
10    2013-01-15     102.586
...          ...         ...
1213  2017-08-25      52.415
1214  2017-08-28      51.040
1215  2017-08-29      51.106
1216  2017-08-30      50.556
1217  2017-08-31      51.986

[1211 rows x 2 columns]

In [42]:
# The reset the index in this case
oil_euro.reset_index(drop=True, inplace=True)
oil_euro

            date  euro_price
0     2013-01-02     102.454
1     2013-01-04     102.432
2     2013-01-08     102.531
3     2013-01-11     102.960
4     2013-01-15     102.586
...          ...         ...
1206  2017-08-25      52.415
1207  2017-08-28      51.040
1208  2017-08-29      51.106
1209  2017-08-30      50.556
1210  2017-08-31      51.986

[1211 rows x 2 columns]