---

# RENAMING AND REORDERING COLUMNS

---

In [1]:
import pandas as pd
import numpy as np

---

## Renaming Columns

In [2]:
product_df = pd.DataFrame({'product':['Dairy', 'Dairy', 'Dairy', 'Vegetables', 'Fruits'],
                           'price':[2.56, 2.56, 4.55, 2.74, 5.44]})
product_df

      product  price
0       Dairy   2.56
1       Dairy   2.56
2       Dairy   4.55
3  Vegetables   2.74
4      Fruits   5.44

In [3]:
# Now make it uppercase - List Comprehension
product_df.columns = [col.upper() for col in product_df.columns]
product_df

      PRODUCT  PRICE
0       Dairy   2.56
1       Dairy   2.56
2       Dairy   4.55
3  Vegetables   2.74
4      Fruits   5.44

In [7]:
product_df = pd.DataFrame({'product':['Dairy', 'Dairy', 'Dairy', 'Vegetables', 'Fruits'],
                           'price':[2.56, 2.56, 4.55, 2.74, 5.44]})

# Changing the names of the columns - METHOD 1
product_df.columns = ['product_name', 'cost']
product_df

  product_name  cost
0        Dairy  2.56
1        Dairy  2.56
2        Dairy  4.55
3   Vegetables  2.74
4       Fruits  5.44

In [8]:
# Now capitalize - Lambda function
product_df.rename(columns=lambda x: x.upper())

  PRODUCT_NAME  COST
0        Dairy  2.56
1        Dairy  2.56
2        Dairy  4.55
3   Vegetables  2.74
4       Fruits  5.44

In [10]:
product_df = pd.DataFrame({'product':['Dairy', 'Dairy', 'Dairy', 'Vegetables', 'Fruits'],
                           'price':[2.56, 2.56, 4.55, 2.74, 5.44]})

# Changing the names of the columns - METHOD 2
product_df.rename(columns={'product':'product_name2', 'price':'cost2'})

  product_name2  cost2
0         Dairy   2.56
1         Dairy   2.56
2         Dairy   4.55
3    Vegetables   2.74
4        Fruits   5.44

---

## Reordering Columns

In [12]:
product_df['product_id'] = range(1, 6)
product_df

      product  price  product_id
0       Dairy   2.56           1
1       Dairy   2.56           2
2       Dairy   4.55           3
3  Vegetables   2.74           4
4      Fruits   5.44           5

In [13]:
product_df.reindex(labels=['product_id', 'product', 'price'], axis=1)

   product_id     product  price
0           1       Dairy   2.56
1           2       Dairy   2.56
2           3       Dairy   4.55
3           4  Vegetables   2.74
4           5      Fruits   5.44

In [15]:
# For permanent change we need to asign otherwise work definetely
product_df

      product  price  product_id
0       Dairy   2.56           1
1       Dairy   2.56           2
2       Dairy   4.55           3
3  Vegetables   2.74           4
4      Fruits   5.44           5

In [16]:
product_df = product_df.reindex(labels=['product_id', 'product', 'price'], axis=1)
product_df

   product_id     product  price
0           1       Dairy   2.56
1           2       Dairy   2.56
2           3       Dairy   4.55
3           4  Vegetables   2.74
4           5      Fruits   5.44

In [17]:
product_df

   product_id     product  price
0           1       Dairy   2.56
1           2       Dairy   2.56
2           3       Dairy   4.55
3           4  Vegetables   2.74
4           5      Fruits   5.44

---

# ASSIGNMENT: MODIFYING COLUMNS

---

In [21]:
transactions = pd.read_csv('Data/transactions.csv')
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [22]:
transactions.columns = ['date', 'store_number', 'transaction_count']
transactions.head()

         date  store_number  transaction_count
0  2013-01-01            25                770
1  2013-01-02             1               2111
2  2013-01-02             2               2358
3  2013-01-02             3               3487
4  2013-01-02             4               1922

In [23]:
transaction = transactions.reindex(labels=['date', 'transaction_count', 'store_number'], axis=1)
transaction.head()

         date  transaction_count  store_number
0  2013-01-01                770            25
1  2013-01-02               2111             1
2  2013-01-02               2358             2
3  2013-01-02               3487             3
4  2013-01-02               1922             4