---

# THE MAP METHOD

---

The `.map()` method **maps the values to a column or an entire DataFrame**

    - You can pass a dictionary with existing values as the keys, and new values as the values

In [2]:
import numpy as np
import pandas as pd

In [6]:
product_df = pd.DataFrame({'product_id':[1, 2, 3, 4, 5],
                           'product' : ['Dairy', 'Dairy', 'Dairy', 'Vegetables', 'Fruits'],
                           'price': [2.56, 2.56, 4.55, 2.74, 5.44]
                          })
product_df

   product_id     product  price
0           1       Dairy   2.56
1           2       Dairy   2.56
2           3       Dairy   4.55
3           4  Vegetables   2.74
4           5      Fruits   5.44

In [9]:
# EXAMPLE NO.1 - Mapping in a new column

mapping_dict = {'Dairy': 'Non-Vegan', 'Vegetables':'Vegan', 'Fruits':'Vegan'}

product_df1 = product_df.copy()
product_df1['Vegan?'] = product_df1['product'].map(mapping_dict)
product_df1

   product_id     product  price     Vegan?
0           1       Dairy   2.56  Non-Vegan
1           2       Dairy   2.56  Non-Vegan
2           3       Dairy   4.55  Non-Vegan
3           4  Vegetables   2.74      Vegan
4           5      Fruits   5.44      Vegan

In [10]:
# EXAMPLE NO.2 - Mapping on the same column
product_df2 = product_df.copy()

product_df2['price'] = product_df2['price'].map(lambda x: f'${x}')
product_df2

   product_id     product  price
0           1       Dairy  $2.56
1           2       Dairy  $2.56
2           3       Dairy  $4.55
3           4  Vegetables  $2.74
4           5      Fruits  $5.44

---

In [11]:
retail = pd.read_csv('Data/retail_2016_2017.csv')
retail.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [12]:
retail.family.value_counts()

family
AUTOMOTIVE                    31968
BABY CARE                     31968
BEAUTY                        31968
BEVERAGES                     31968
BOOKS                         31968
BREAD/BAKERY                  31968
CELEBRATION                   31968
CLEANING                      31968
DAIRY                         31968
DELI                          31968
EGGS                          31968
FROZEN FOODS                  31968
GROCERY I                     31968
GROCERY II                    31968
HARDWARE                      31968
HOME AND KITCHEN I            31968
HOME AND KITCHEN II           31968
HOME APPLIANCES               31968
HOME CARE                     31968
LADIESWEAR                    31968
LAWN AND GARDEN               31968
LINGERIE                      31968
LIQUOR,WINE,BEER              31968
MAGAZINES                     31968
MEATS                         31968
PERSONAL CARE                 31968
PET SUPPLIES                  31968
PLAYERS AND ELECTRONICS       31968
POULTRY                       31968
PREPARED FOODS                31968
PRODUCE                       31968
SCHOOL AND OFFICE SUPPLIES    31968
SEAFOOD                       31968
Name: count, dtype: int64

In [18]:
product_category_dict = {
    'PRODUCE': 'GROCERY',
    'POULTRY': 'GROCERY',
    'GROCERY I': 'GROCERY',
    'GROCERY II': 'GROCERY',
    'EGGS': 'GROCERY'
}

retail.family.map(product_category_dict).value_counts(dropna=False)

family
NaN        895104
GROCERY    159840
Name: count, dtype: int64

## How to solve this mapping problem - possible solution

---

`PRO TIP`: Be sure to MAP all the categories of `family` column. Otherwise you'll include several `NaN` values to all categories not specified on the original column

---

In [25]:
mv_dict = {}

for value in retail.family.values:
    if value in product_category_dict.keys():
        mv_dict[value] = product_category_dict[value]
    else:
        mv_dict[value] = value

# now we'll map again...
retail.family.map(mv_dict).value_counts()

family
GROCERY                       159840
BABY CARE                      31968
BEAUTY                         31968
BEVERAGES                      31968
AUTOMOTIVE                     31968
BOOKS                          31968
BREAD/BAKERY                   31968
CLEANING                       31968
CELEBRATION                    31968
DAIRY                          31968
DELI                           31968
FROZEN FOODS                   31968
HARDWARE                       31968
HOME AND KITCHEN I             31968
HOME AND KITCHEN II            31968
HOME APPLIANCES                31968
HOME CARE                      31968
LADIESWEAR                     31968
LAWN AND GARDEN                31968
LINGERIE                       31968
LIQUOR,WINE,BEER               31968
MAGAZINES                      31968
MEATS                          31968
PERSONAL CARE                  31968
PET SUPPLIES                   31968
PLAYERS AND ELECTRONICS        31968
PREPARED FOODS                 31968
SCHOOL AND OFFICE SUPPLIES     31968
SEAFOOD                        31968
Name: count, dtype: int64

In [26]:
mv_dict

{'AUTOMOTIVE': 'AUTOMOTIVE',
 'BABY CARE': 'BABY CARE',
 'BEAUTY': 'BEAUTY',
 'BEVERAGES': 'BEVERAGES',
 'BOOKS': 'BOOKS',
 'BREAD/BAKERY': 'BREAD/BAKERY',
 'CELEBRATION': 'CELEBRATION',
 'CLEANING': 'CLEANING',
 'DAIRY': 'DAIRY',
 'DELI': 'DELI',
 'EGGS': 'GROCERY',
 'FROZEN FOODS': 'FROZEN FOODS',
 'GROCERY I': 'GROCERY',
 'GROCERY II': 'GROCERY',
 'HARDWARE': 'HARDWARE',
 'HOME AND KITCHEN I': 'HOME AND KITCHEN I',
 'HOME AND KITCHEN II': 'HOME AND KITCHEN II',
 'HOME APPLIANCES': 'HOME APPLIANCES',
 'HOME CARE': 'HOME CARE',
 'LADIESWEAR': 'LADIESWEAR',
 'LAWN AND GARDEN': 'LAWN AND GARDEN',
 'LINGERIE': 'LINGERIE',
 'LIQUOR,WINE,BEER': 'LIQUOR,WINE,BEER',
 'MAGAZINES': 'MAGAZINES',
 'MEATS': 'MEATS',
 'PERSONAL CARE': 'PERSONAL CARE',
 'PET SUPPLIES': 'PET SUPPLIES',
 'PLAYERS AND ELECTRONICS': 'PLAYERS AND ELECTRONICS',
 'POULTRY': 'GROCERY',
 'PREPARED FOODS': 'PREPARED FOODS',
 'PRODUCE': 'GROCERY',
 'SCHOOL AND OFFICE SUPPLIES': 'SCHOOL AND OFFICE SUPPLIES',
 'SEAFOOD': 'SEAFOOD'}