---
<br>

$$\LARGE \text{GROUPBY METHOD}$$

<br>

---

<br>

In this section we'll cover `aggregating & reshaping` DataFrames, including Grouping columns, performing Aggregation calculations, and Pivoting & Unpivoting data.

In [1]:
import numpy as np
import pandas as pd

In [2]:
retail = pd.read_csv('Data/retail_2016_2017.csv')
retail.head(3)

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0

In [3]:
retail[['sales', 'onpromotion']].sample(100).sum().round(2)

sales          45955.61
onpromotion      714.00
dtype: float64

In [4]:
retail[['sales', 'onpromotion']].sample(100).mean().round(2)

sales          330.19
onpromotion      4.49
dtype: float64

<br><br>

---

But what if you want multiple aggregate statistics, or summarized statistics by groups?

In [5]:
premier_league = pd.read_excel('Data/premier_league_games_full.xlsx')
premier_league.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

In [6]:
premier_league.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3040 entries, 0 to 3039
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           3040 non-null   int64
 1   league_name  3040 non-null   object
 2   season       3040 non-null   object
 3   HomeTeam     3040 non-null   object
 4   AwayTeam     3040 non-null   object
 5   HomeGoals    3040 non-null   int64
 6   AwayGoals    3040 non-null   int64
dtypes: int64(3), object(4)
memory usage: 166.4+ KB

In [7]:
premier_league.describe()

                id    HomeGoals    AwayGoals
count  3040.000000  3040.000000  3040.000000
mean   3248.500000     1.550987     1.159539
std     877.716735     1.311615     1.144629
min    1729.000000     0.000000     0.000000
25%    2488.750000     1.000000     0.000000
50%    3248.500000     1.000000     1.000000
75%    4008.250000     2.000000     2.000000
max    4768.000000     9.000000     6.000000

---

# 1. Working with `.groupby()` Method

>**Grouping a DataFrame** allows you to aggregate the data at a different level.
>
>   - For example, transform daily data into monthly, roll up transactions level data by store, etc...

>To group data, use the `.groupby()` method and specify a column to group by
>
>   - The grouped column becomes the index by default

In [8]:
retail = pd.read_csv('Data/retail_2016_2017.csv')
retail.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [9]:
print('----------- This is a Series result ------------')
retail.groupby('family')['sales'].sum().head()

----------- This is a Series result ------------

family
AUTOMOTIVE       226139.0
BABY CARE          7903.0
BEAUTY           166189.0
BEVERAGES     105700279.0
BOOKS              6438.0
Name: sales, dtype: float64

In [10]:
print('----------- This is a DataFrame result ------------')
retail.groupby('family')[['sales']].sum().head()

----------- This is a DataFrame result ------------

                  sales
family
AUTOMOTIVE     226139.0
BABY CARE        7903.0
BEAUTY         166189.0
BEVERAGES   105700279.0
BOOKS            6438.0

---

## LABORATORY

---

In [11]:
premier_league.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

In [12]:
premier_league.groupby('HomeTeam')[['HomeGoals']].sum().sort_values(by='HomeGoals', ascending=False).head(10)

                   HomeGoals
HomeTeam
Manchester City          365
Manchester United        338
Chelsea                  333
Arsenal                  306
Liverpool                294
Everton                  258
Tottenham Hotspur        255
Stoke City               204
Newcastle United         199
West Ham United          195

In [13]:
premier_league.groupby('AwayTeam')[['AwayGoals']].sum().sort_values(by='AwayGoals', ascending=False).head(10)

                   AwayGoals
AwayTeam
Arsenal                  267
Chelsea                  250
Manchester United        244
Manchester City          241
Liverpool                237
Tottenham Hotspur        226
Everton                  181
Aston Villa              156
Sunderland               149
West Ham United          131

---

## ASSIGNMENT: GROUPBY

---

In [14]:
transactions = pd.read_csv('Data/transactions.csv')
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [16]:
transactions.groupby('store_nbr')[['transactions']].sum().sort_values('transactions', ascending=False).iloc[:10]

           transactions
store_nbr
44              7273093
47              6535810
45              6201115
46              5990113
3               5366350
48              5107785
8               4637971
49              4574103
50              4384444
11              3972488

<br><br>

---

# 2. Grouping By Multiple Columns

>You can **group by multiple columns** by passing the list of columns into `.groupby()`
>
>   - This creates a multi-index object with an index for each column the data was grouped by

In [17]:
retail.head()

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0
3  1945947  2016-01-01          1   BEVERAGES    0.0            0
4  1945948  2016-01-01          1       BOOKS    0.0            0

In [18]:
retail.groupby(['family', 'store_nbr'])[['sales']].sum()

                             sales
family     store_nbr
AUTOMOTIVE 1           2524.000000
           2           3918.000000
           3           6790.000000
           4           2565.000000
           5           3667.000000
...                            ...
SEAFOOD    50         12773.966999
           51         34250.948976
           52          1219.475999
           53          3745.180001
           54          1082.000000

[1782 rows x 1 columns]

In [19]:
retail.groupby(['family', 'store_nbr'], as_index=False)[['sales']].sum()

          family  store_nbr         sales
0     AUTOMOTIVE          1   2524.000000
1     AUTOMOTIVE          2   3918.000000
2     AUTOMOTIVE          3   6790.000000
3     AUTOMOTIVE          4   2565.000000
4     AUTOMOTIVE          5   3667.000000
...          ...        ...           ...
1777     SEAFOOD         50  12773.966999
1778     SEAFOOD         51  34250.948976
1779     SEAFOOD         52   1219.475999
1780     SEAFOOD         53   3745.180001
1781     SEAFOOD         54   1082.000000

[1782 rows x 3 columns]

---

## LABORATORY

In [20]:
premier_league.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

In [22]:
premier_league.groupby(['HomeTeam', 'season'])[['HomeGoals']].sum()

                                   HomeGoals
HomeTeam                season
Arsenal                 2008/2009         31
                        2009/2010         48
                        2010/2011         33
                        2011/2012         39
                        2012/2013         47
...                                      ...
Wigan Athletic          2011/2012         22
                        2012/2013         26
Wolverhampton Wanderers 2009/2010         13
                        2010/2011         30
                        2011/2012         19

[160 rows x 1 columns]

In [23]:
premier_league.groupby(['HomeTeam', 'season'], as_index=False)['HomeGoals'].sum()

                    HomeTeam     season  HomeGoals
0                    Arsenal  2008/2009         31
1                    Arsenal  2009/2010         48
2                    Arsenal  2010/2011         33
3                    Arsenal  2011/2012         39
4                    Arsenal  2012/2013         47
..                       ...        ...        ...
155           Wigan Athletic  2011/2012         22
156           Wigan Athletic  2012/2013         26
157  Wolverhampton Wanderers  2009/2010         13
158  Wolverhampton Wanderers  2010/2011         30
159  Wolverhampton Wanderers  2011/2012         19

[160 rows x 3 columns]

In [28]:
premier_league.groupby(['season', 'HomeTeam'], sort=False)[['HomeGoals']].sum().sort_values(['season', 'HomeGoals'], ascending=[True, False])

                                HomeGoals
season    HomeTeam
2008/2009 Manchester United            43
          Liverpool                    41
          Manchester City              40
          Chelsea                      33
          Arsenal                      31
...                                   ...
2015/2016 West Bromwich Albion         20
          Swansea City                 20
          Watford                      20
          Crystal Palace               19
          Aston Villa                  14

[160 rows x 1 columns]

In [38]:
premier_league.groupby(['season', 'HomeTeam'], as_index=False)[['HomeGoals']].sum().query("HomeTeam == 'Arsenal'")

        season HomeTeam  HomeGoals
0    2008/2009  Arsenal         31
20   2009/2010  Arsenal         48
40   2010/2011  Arsenal         33
60   2011/2012  Arsenal         39
80   2012/2013  Arsenal         47
100  2013/2014  Arsenal         36
120  2014/2015  Arsenal         41
140  2015/2016  Arsenal         31

---

## ASSIGNMENT: GROUPBY MULTIPLE COLUMNS

In [39]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [42]:
transactions = transactions.assign(
    month = transactions.date.astype('datetime64[ns]').dt.month,
    year = transactions.date.astype('datetime64[ns]').dt.year,
    day_of_week = transactions.date.astype('datetime64[ns]').dt.dayofweek
)
transactions.head()

         date  store_nbr  transactions  month  year  day_of_week
0  2013-01-01         25           770      1  2013            1
1  2013-01-02          1          2111      1  2013            2
2  2013-01-02          2          2358      1  2013            2
3  2013-01-02          3          3487      1  2013            2
4  2013-01-02          4          1922      1  2013            2

<br><br>

---
---

`PRO TIP`: When working with date columns. I would save some writting code on the `.assign()` method by:

<br>

>
>REDUCED METHOD:
>```python
>transactions = pd.read_csv('Data/transactions.csv', parse_date=['date'])
>
>transactions = transactions.assign(month = transactions.date.dt.month)
>```
<br>

>
>LARGE METHOD:
>```python
>transactions = pd.read_csv('Data/transactions.csv')
>
>transactions = transactions.assign(month = transactions.date.astype('datetime64[ns]').dt.month)
>```

---
---

<br>

In [46]:
# by using the parameter 'parse_dates' we automatically set that column into a datetime format
trans_actions = pd.read_csv('Data/transactions.csv', parse_dates=['date'])
trans_actions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  datetime64[ns]
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 1.9 MB

In [47]:
trans_actions.head(3)

        date  store_nbr  transactions
0 2013-01-01         25           770
1 2013-01-02          1          2111
2 2013-01-02          2          2358

<br><br>

In [49]:
transactions.groupby(['store_nbr', 'month'], as_index=False)['transactions'].sum().sort_values(by=['month', 'transactions'], 
                                                                                               ascending=[True, False])

     store_nbr  month  transactions
516         44      1        628438
552         47      1        568824
528         45      1        538370
540         46      1        522763
24           3      1        463260
..         ...    ...           ...
383         32     12         86167
251         21     12         84128
503         42     12         76741
347         29     12         76627
263         22     12         50650

[641 rows x 3 columns]

In [50]:
# this is a more professional way to code
(transactions
    .groupby(['store_nbr', 'month'], as_index=False)['transactions']
    .sum()
    .sort_values(by=['month', 'transactions'], ascending=[True, False])
)

     store_nbr  month  transactions
516         44      1        628438
552         47      1        568824
528         45      1        538370
540         46      1        522763
24           3      1        463260
..         ...    ...           ...
383         32     12         86167
251         21     12         84128
503         42     12         76741
347         29     12         76627
263         22     12         50650

[641 rows x 3 columns]