---

# MODIFYING MULTI-INDICES

---

In [1]:
import numpy as np
import pandas as pd

In [2]:
retail = pd.read_csv('Data/retail_2016_2017.csv')
retail.head(3)

        id        date  store_nbr      family  sales  onpromotion
0  1945944  2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945  2016-01-01          1   BABY CARE    0.0            0
2  1945946  2016-01-01          1      BEAUTY    0.0            0

In [3]:
sale_sum = retail.groupby(['family', 'store_nbr', 'onpromotion'])[['sales']].sum()
sale_sum

                                        sales
family     store_nbr onpromotion
AUTOMOTIVE 1         0            2458.000000
                     1              66.000000
           2         0            3835.000000
                     1              83.000000
           3         0            6636.000000
...                                       ...
SEAFOOD    53        4             335.868001
                     5              49.146000
           54        0             800.000000
                     1             203.000000
                     2              79.000000

[34099 rows x 1 columns]

There are several ways to **modify multi-index DataFrames**:

---

1. `Reset the Index`: Moves the index levels back to DataFrame columns

In [4]:
# Returns into an original DataFrame
sale_sum.reset_index()

           family  store_nbr  onpromotion        sales
0      AUTOMOTIVE          1            0  2458.000000
1      AUTOMOTIVE          1            1    66.000000
2      AUTOMOTIVE          2            0  3835.000000
3      AUTOMOTIVE          2            1    83.000000
4      AUTOMOTIVE          3            0  6636.000000
...           ...        ...          ...          ...
34094     SEAFOOD         53            4   335.868001
34095     SEAFOOD         53            5    49.146000
34096     SEAFOOD         54            0   800.000000
34097     SEAFOOD         54            1   203.000000
34098     SEAFOOD         54            2    79.000000

[34099 rows x 4 columns]

---

2. `Swap the Index Level`: Changes the hierarchy for the index levels

In [5]:
sale_sum.swaplevel()

                                        sales
family     onpromotion store_nbr
AUTOMOTIVE 0           1          2458.000000
           1           1            66.000000
           0           2          3835.000000
           1           2            83.000000
           0           3          6636.000000
...                                       ...
SEAFOOD    4           53          335.868001
           5           53           49.146000
           0           54          800.000000
           1           54          203.000000
           2           54           79.000000

[34099 rows x 1 columns]

---

3. `Drop an Index Level`: Drops an index level from the DataFrame entirely

In [6]:
sale_sum.droplevel('family')

                             sales
store_nbr onpromotion
1         0            2458.000000
          1              66.000000
2         0            3835.000000
          1              83.000000
3         0            6636.000000
...                            ...
53        4             335.868001
          5              49.146000
54        0             800.000000
          1             203.000000
          2              79.000000

[34099 rows x 1 columns]

<span style='color:orange'>
    
`NOTE:` Be careful with this method. You **may lose important information**


<br><br>

---

## LABORATORY

In [7]:
premier_league = pd.read_excel('Data/premier_league_games_full.xlsx')
premier_league.head(3)

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1

In [8]:
agg_league = premier_league.groupby(['season', 'HomeTeam']).agg({'HomeGoals':['sum', 'mean']})
agg_league

                               HomeGoals
                                     sum      mean
season    HomeTeam
2008/2009 Arsenal                     31  1.631579
          Aston Villa                 27  1.421053
          Blackburn Rovers            22  1.157895
          Bolton Wanderers            21  1.105263
          Chelsea                     33  1.736842
...                                  ...       ...
2015/2016 Swansea City                20  1.052632
          Tottenham Hotspur           35  1.842105
          Watford                     20  1.052632
          West Bromwich Albion        20  1.052632
          West Ham United             34  1.789474

[160 rows x 2 columns]

In [9]:
agg_league.droplevel(0, axis=1)

                                sum      mean
season    HomeTeam
2008/2009 Arsenal                31  1.631579
          Aston Villa            27  1.421053
          Blackburn Rovers       22  1.157895
          Bolton Wanderers       21  1.105263
          Chelsea                33  1.736842
...                             ...       ...
2015/2016 Swansea City           20  1.052632
          Tottenham Hotspur      35  1.842105
          Watford                20  1.052632
          West Bromwich Albion   20  1.052632
          West Ham United        34  1.789474

[160 rows x 2 columns]

In [10]:
agg_league.swaplevel()

                               HomeGoals
                                     sum      mean
HomeTeam             season
Arsenal              2008/2009        31  1.631579
Aston Villa          2008/2009        27  1.421053
Blackburn Rovers     2008/2009        22  1.157895
Bolton Wanderers     2008/2009        21  1.105263
Chelsea              2008/2009        33  1.736842
...                                  ...       ...
Swansea City         2015/2016        20  1.052632
Tottenham Hotspur    2015/2016        35  1.842105
Watford              2015/2016        20  1.052632
West Bromwich Albion 2015/2016        20  1.052632
West Ham United      2015/2016        34  1.789474

[160 rows x 2 columns]

---

## ASSIGNMENT: MULTI-INDEX DATAFRAMES

In [11]:
transactions = pd.read_csv('Data/transactions.csv', parse_dates=['date'])
transactions = transactions.assign(month = transactions.date.dt.month)
transactions.head()

        date  store_nbr  transactions  month
0 2013-01-01         25           770      1
1 2013-01-02          1          2111      1
2 2013-01-02          2          2358      1
3 2013-01-02          3          3487      1
4 2013-01-02          4          1922      1

In [12]:
grouped_df = (
    transactions.groupby(['store_nbr', 'month'])
    .agg({'transactions':['sum', 'mean', 'max']})
    .sort_values(by=['month', ('transactions', 'sum')], ascending=[True, False])    
)
grouped_df

                transactions
                         sum         mean   max
store_nbr month
44        1           628438  4246.202703  5701
47        1           568824  3843.405405  5234
45        1           538370  3637.635135  5218
46        1           522763  3532.182432  5600
3         1           463260  3151.428571  3920
...                      ...          ...   ...
32        12           86167   718.058333  1497
21        12           84128  1402.133333  2730
42        12           76741  1279.016667  2368
29        12           76627  1277.116667  2261
22        12           50650   844.166667  1524

[641 rows x 3 columns]

---

NOW: Convert the Multi-Index DataFrame into an `Integer-Based Index`

In [13]:
regular_df = grouped_df.droplevel(level=0, axis=1)
regular_df

                    sum         mean   max
store_nbr month
44        1      628438  4246.202703  5701
47        1      568824  3843.405405  5234
45        1      538370  3637.635135  5218
46        1      522763  3532.182432  5600
3         1      463260  3151.428571  3920
...                 ...          ...   ...
32        12      86167   718.058333  1497
21        12      84128  1402.133333  2730
42        12      76741  1279.016667  2368
29        12      76627  1277.116667  2261
22        12      50650   844.166667  1524

[641 rows x 3 columns]

In [14]:
regular_df = regular_df.reset_index()
regular_df

     store_nbr  month     sum         mean   max
0           44      1  628438  4246.202703  5701
1           47      1  568824  3843.405405  5234
2           45      1  538370  3637.635135  5218
3           46      1  522763  3532.182432  5600
4            3      1  463260  3151.428571  3920
..         ...    ...     ...          ...   ...
636         32     12   86167   718.058333  1497
637         21     12   84128  1402.133333  2730
638         42     12   76741  1279.016667  2368
639         29     12   76627  1277.116667  2261
640         22     12   50650   844.166667  1524

[641 rows x 5 columns]