---

# MELTING DATAFRAMES

---

The `.melt()` method will ***unpivot a DataFrame***, or convert columns into rows. This is great for turning a "wide" data table into a "long" format.

In [1]:
import numpy as np
import pandas as pd

In [2]:
country_revenue = pd.DataFrame({
    'country':['Algeria', 'Egypt', 'Nigeria', 'South Africa'],
    '2000':[151, 204, 277, 190],
    '2001':[171, 214, 301, 211],
    '2002':[176, 227, 311, 224],
    '2003':[184, 241, 342, 243]
})
country_revenue

        country  2000  2001  2002  2003
0       Algeria   151   171   176   184
1         Egypt   204   214   227   241
2       Nigeria   277   301   311   342
3  South Africa   190   211   224   243

---

## 1. Simple use of `.melt()` Method

In [3]:
country_revenue.melt()

   variable         value
0   country       Algeria
1   country         Egypt
2   country       Nigeria
3   country  South Africa
4      2000           151
5      2000           204
6      2000           277
7      2000           190
8      2001           171
9      2001           214
10     2001           301
11     2001           211
12     2002           176
13     2002           227
14     2002           311
15     2002           224
16     2003           184
17     2003           241
18     2003           342
19     2003           243

In [5]:
country_revenue

        country  2000  2001  2002  2003
0       Algeria   151   171   176   184
1         Egypt   204   214   227   241
2       Nigeria   277   301   311   342
3  South Africa   190   211   224   243

---

## 2. Using Parameters of `.melt()` Method

In [6]:
country_revenue.melt(id_vars='country')

         country variable  value
0        Algeria     2000    151
1          Egypt     2000    204
2        Nigeria     2000    277
3   South Africa     2000    190
4        Algeria     2001    171
5          Egypt     2001    214
6        Nigeria     2001    301
7   South Africa     2001    211
8        Algeria     2002    176
9          Egypt     2002    227
10       Nigeria     2002    311
11  South Africa     2002    224
12       Algeria     2003    184
13         Egypt     2003    241
14       Nigeria     2003    342
15  South Africa     2003    243

---

We can also select the columns to melt and name the `variable` & `value` columns

In [7]:
country_revenue

        country  2000  2001  2002  2003
0       Algeria   151   171   176   184
1         Egypt   204   214   227   241
2       Nigeria   277   301   311   342
3  South Africa   190   211   224   243

In [8]:
country_revenue.melt(id_vars='country',
                     value_vars=['2001', '2002', '2003'],
                     var_name='year',
                     value_name='GDP',)

         country  year  GDP
0        Algeria  2001  171
1          Egypt  2001  214
2        Nigeria  2001  301
3   South Africa  2001  211
4        Algeria  2002  176
5          Egypt  2002  227
6        Nigeria  2002  311
7   South Africa  2002  224
8        Algeria  2003  184
9          Egypt  2003  241
10       Nigeria  2003  342
11  South Africa  2003  243

---

## LABORATORY

In [9]:
pm = pd.read_excel('Data/premier_league_games_full.xlsx')
pm.head()

,id,league_name,season,HomeTeam,AwayTeam,HomeGoals,AwayGoals
0,1729,England Premier League,2008/2009,Manchester United,Newcastle United,1,1
1,1730,England Premier League,2008/2009,Arsenal,West Bromwich Albion,1,0
2,1731,England Premier League,2008/2009,Sunderland,Liverpool,0,1
3,1732,England Premier League,2008/2009,West Ham United,Wigan Athletic,2,1
4,1733,England Premier League,2008/2009,Aston Villa,Manchester City,4,2

In [10]:
pm = (pm.query("HomeTeam in ['Arsenal', 'Chelsea', 'Everton']")
    .pivot_table(index='HomeTeam', columns='season', values='HomeGoals', aggfunc='mean')
    )
pm

season,2008/2009,2009/2010,2010/2011,2011/2012,2012/2013,2013/2014,2014/2015,2015/2016
HomeTeam,,,,,,,,
Arsenal,1.631579,2.526316,1.736842,2.052632,2.473684,1.894737,2.157895,1.631579
Chelsea,1.736842,3.578947,2.052632,2.157895,2.157895,2.263158,1.894737,1.684211
Everton,1.631579,1.842105,1.631579,1.473684,1.736842,2.000000,1.421053,1.842105

In [15]:
# we need to first reset the index. Otherwise we loose "HomeTeam"...
pm.melt()

       season     value
0   2008/2009  1.631579
1   2008/2009  1.736842
2   2008/2009  1.631579
3   2009/2010  2.526316
4   2009/2010  3.578947
5   2009/2010  1.842105
6   2010/2011  1.736842
7   2010/2011  2.052632
8   2010/2011  1.631579
9   2011/2012  2.052632
10  2011/2012  2.157895
11  2011/2012  1.473684
12  2012/2013  2.473684
13  2012/2013  2.157895
14  2012/2013  1.736842
15  2013/2014  1.894737
16  2013/2014  2.263158
17  2013/2014  2.000000
18  2014/2015  2.157895
19  2014/2015  1.894737
20  2014/2015  1.421053
21  2015/2016  1.631579
22  2015/2016  1.684211
23  2015/2016  1.842105

In [16]:
# If we "reset index" we have the HomeTeam
pm.reset_index().melt()

       season     value
0    HomeTeam   Arsenal
1    HomeTeam   Chelsea
2    HomeTeam   Everton
3   2008/2009  1.631579
4   2008/2009  1.736842
5   2008/2009  1.631579
6   2009/2010  2.526316
7   2009/2010  3.578947
8   2009/2010  1.842105
9   2010/2011  1.736842
10  2010/2011  2.052632
11  2010/2011  1.631579
12  2011/2012  2.052632
13  2011/2012  2.157895
14  2011/2012  1.473684
15  2012/2013  2.473684
16  2012/2013  2.157895
17  2012/2013  1.736842
18  2013/2014  1.894737
19  2013/2014  2.263158
20  2013/2014       2.0
21  2014/2015  2.157895
22  2014/2015  1.894737
23  2014/2015  1.421053
24  2015/2016  1.631579
25  2015/2016  1.684211
26  2015/2016  1.842105

In [17]:
# And the melting will successfully show...
pm.reset_index().melt(id_vars='HomeTeam')

   HomeTeam     season     value
0   Arsenal  2008/2009  1.631579
1   Chelsea  2008/2009  1.736842
2   Everton  2008/2009  1.631579
3   Arsenal  2009/2010  2.526316
4   Chelsea  2009/2010  3.578947
5   Everton  2009/2010  1.842105
6   Arsenal  2010/2011  1.736842
7   Chelsea  2010/2011  2.052632
8   Everton  2010/2011  1.631579
9   Arsenal  2011/2012  2.052632
10  Chelsea  2011/2012  2.157895
11  Everton  2011/2012  1.473684
12  Arsenal  2012/2013  2.473684
13  Chelsea  2012/2013  2.157895
14  Everton  2012/2013  1.736842
15  Arsenal  2013/2014  1.894737
16  Chelsea  2013/2014  2.263158
17  Everton  2013/2014  2.000000
18  Arsenal  2014/2015  2.157895
19  Chelsea  2014/2015  1.894737
20  Everton  2014/2015  1.421053
21  Arsenal  2015/2016  1.631579
22  Chelsea  2015/2016  1.684211
23  Everton  2015/2016  1.842105

In [18]:
# Now we add 'value_vars'
pm.reset_index().melt(id_vars='HomeTeam',
                      value_vars=['2008/2009', '2009/2010', '2010/2011'],
                     )

  HomeTeam     season     value
0  Arsenal  2008/2009  1.631579
1  Chelsea  2008/2009  1.736842
2  Everton  2008/2009  1.631579
3  Arsenal  2009/2010  2.526316
4  Chelsea  2009/2010  3.578947
5  Everton  2009/2010  1.842105
6  Arsenal  2010/2011  1.736842
7  Chelsea  2010/2011  2.052632
8  Everton  2010/2011  1.631579

In [19]:
pm.reset_index().melt(id_vars='HomeTeam',
                      value_vars=['2008/2009', '2009/2010', '2010/2011'],
                      value_name='avg_goals')

  HomeTeam     season  avg_goals
0  Arsenal  2008/2009   1.631579
1  Chelsea  2008/2009   1.736842
2  Everton  2008/2009   1.631579
3  Arsenal  2009/2010   2.526316
4  Chelsea  2009/2010   3.578947
5  Everton  2009/2010   1.842105
6  Arsenal  2010/2011   1.736842
7  Chelsea  2010/2011   2.052632
8  Everton  2010/2011   1.631579

---

## ASSIGNMENT: PIVOT & MELT

In [23]:
transactions = pd.read_csv('Data/transactions.csv')

transactions = transactions.assign(
    target_pct = transactions.transactions / 2500,
    met_target = (transactions.transactions / 2500) >=1,
    bonus_payable = ((transactions.transactions / 2500) >=1) * 100,
    month = transactions.date.astype('datetime64[ns]').dt.month,
    day_of_week = transactions.date.astype('datetime64[ns]').dt.dayofweek)
    
transactions.head(3)

,date,store_nbr,transactions,target_pct,met_target,bonus_payable,month,day_of_week
0,2013-01-01,25,770,0.3080,False,0,1,1
1,2013-01-02,1,2111,0.8444,False,0,1,2
2,2013-01-02,2,2358,0.9432,False,0,1,2

In [24]:
transactions = transactions.assign(
    store_avg_trans = transactions.groupby(['store_nbr', 'day_of_week'])['transactions'].transform('mean'),
    trans_vs_avg = lambda x: x['transactions'] - x['store_avg_trans']
)
transactions

,date,store_nbr,transactions,target_pct,met_target,bonus_payable,month,day_of_week,store_avg_trans,trans_vs_avg
0,2013-01-01,25,770,0.3080,False,0,1,1,740.245690,29.754310
1,2013-01-02,1,2111,0.8444,False,0,1,2,1870.782427,240.217573
2,2013-01-02,2,2358,0.9432,False,0,1,2,1952.652720,405.347280
3,2013-01-02,3,3487,1.3948,True,100,1,2,3142.682008,344.317992
4,2013-01-02,4,1922,0.7688,False,0,1,2,1499.569038,422.430962
...,...,...,...,...,...,...,...,...,...,...
83483,2017-08-15,50,2804,1.1216,True,100,8,1,2342.410788,461.589212
83484,2017-08-15,51,1573,0.6292,False,0,8,1,1548.448133,24.551867
83485,2017-08-15,52,2255,0.9020,False,0,8,1,1892.588235,362.411765
83486,2017-08-15,53,932,0.3728,False,0,8,1,877.214286,54.785714
83487,2017-08-15,54,802,0.3208,False,0,8,1,817.721992,-15.721992

---
---

In [54]:
pivot_transactions = (transactions
    .query("store_nbr <= 11 and bonus_payable > 0")
    .pivot_table(index='store_nbr', columns='day_of_week', 
                 values='bonus_payable', aggfunc='sum')
    .style.format("{:.2f}")
    .background_gradient(cmap='RdYlGn', axis=1)
)

pivot_transactions

In [58]:
melt_transactions = (transactions
    .query("store_nbr <= 11 and bonus_payable > 0")
    .pivot_table(index='store_nbr', columns='day_of_week', 
                 values='bonus_payable', aggfunc='sum')
    .reset_index()
    .melt(id_vars='store_nbr',value_name='bonus_payable')
)

melt_transactions

    store_nbr day_of_week  bonus_payable
0           1           0          200.0
1           2           0          300.0
2           3           0        24000.0
3           4           0          200.0
4           5           0          200.0
..        ...         ...            ...
65          6           6          300.0
66          7           6            NaN
67          8           6        20000.0
68          9           6         5100.0
69         11           6        17600.0

[70 rows x 3 columns]