---

# CONVERTING TO DATETIMES

---

<br><br>

> The `.astype()` method can convert strings to datetimes, but has some **limitations**:
>
>- Any values that Pandas can't correctly identify as dates will return an error.

In [1]:
import pandas as pd
import numpy as np
import datetime

In [3]:
df = pd.DataFrame({'order_date':['2021-04-04', '2021-05-23'],
                   'delivery_date':['2021-04-07', pd.NA]})

print(df.info())
print('-'*60)

df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_date     2 non-null      object
 1   delivery_date  1 non-null      object
dtypes: object(2)
memory usage: 164.0+ bytes
None
------------------------------------------------------------

   order_date delivery_date
0  2021-04-04    2021-04-07
1  2021-05-23          <NA>

In [4]:
df = df.astype({'order_date':'datetime64[ns]', 
           'delivery_date':'datetime64[ns]'})

print(df.info())
print('-'*60)

df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_date     2 non-null      datetime64[ns]
 1   delivery_date  1 non-null      datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 164.0 bytes
None
------------------------------------------------------------

  order_date delivery_date
0 2021-04-04    2021-04-07
1 2021-05-23           NaT

>---
>`.astype()` METHOD
>
>The `.astype()` method can convert strings to datetimes, but has som limitations:
>
>- Any values that Pandas can't correctly identify as dates will return an error
>
>- Ignoring the errors will return the Series as an `object` data type, not `datetime64[ns]`

<br><br>

>---
>`.to_datetime()` FUNCTION
>
>The `.to_datetime()` function is a more flexible option for converting datetimes

<br><br>

>---
>NOTE: `NaT` stands for **Not a Time**

In [5]:
# The DataFrame
df = pd.DataFrame({'order_date':['2021-04-04', '2021-05-23'],
                   'delivery_date':['2021-04-07', pd.NA]})

# The DateTime Conversion
df['delivery_date'] = pd.to_datetime(df['delivery_date'], 
                                     errors='coerce',
                                     format='%Y-%m-%d',
                                    )
df

   order_date delivery_date
0  2021-04-04    2021-04-07
1  2021-05-23           NaT

<br><br>

---

## LABORATORY

In [7]:
retail = pd.read_parquet('../Data/retail_2016_2017.parquet')
retail.head()

        id       date  store_nbr      family  sales  onpromotion
0  1945944 2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945 2016-01-01          1   BABY CARE    0.0            0
2  1945946 2016-01-01          1      BEAUTY    0.0            0
3  1945947 2016-01-01          1   BEVERAGES    0.0            0
4  1945948 2016-01-01          1       BOOKS    0.0            0

In [8]:
retail.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  datetime64[ns]
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  object
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 100.4 MB

In [13]:
# let's change to np.nan the first 'date' row
retail.loc[0, 'date'] = np.nan

print(retail.info())

retail.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054943 non-null  datetime64[ns]
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  object
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 48.3+ MB
None

        id       date  store_nbr      family  sales  onpromotion
0  1945944        NaT          1  AUTOMOTIVE    0.0            0
1  1945945 2016-01-01          1   BABY CARE    0.0            0
2  1945946 2016-01-01          1      BEAUTY    0.0            0
3  1945947 2016-01-01          1   BEVERAGES    0.0            0
4  1945948 2016-01-01          1       BOOKS    0.0            0

>Note that even we decided to fill the first 'date' row with a NumPy `NaN`.
>
>Since this column is a `datetime64[ns]` that missing value has been changed to a `NaT` value.
>
>And the columns has remained it's `datetime64[ns]`