---

# DATE AND TIME PARTS

---

<br><br>

>---
>While you can also use the `.strftime()` method to **extract datetime components**, it's prefered to use the dedicated `.dt` **accessors**.

In [1]:
import pandas as pd
import numpy as np

In [2]:
retail = pd.read_parquet('../Data/retail_2016_2017.parquet')
retail.head()

        id       date  store_nbr      family  sales  onpromotion
0  1945944 2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945 2016-01-01          1   BABY CARE    0.0            0
2  1945946 2016-01-01          1      BEAUTY    0.0            0
3  1945947 2016-01-01          1   BEVERAGES    0.0            0
4  1945948 2016-01-01          1       BOOKS    0.0            0

In [3]:
retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  datetime64[ns]
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  object
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 48.3+ MB

In [4]:
# Show the date
retail['date'].dt.date

0          2016-01-01
1          2016-01-01
2          2016-01-01
3          2016-01-01
4          2016-01-01
              ...
1054939    2017-08-15
1054940    2017-08-15
1054941    2017-08-15
1054942    2017-08-15
1054943    2017-08-15
Name: date, Length: 1054944, dtype: object

In [5]:
# Show the year
retail['date'].dt.year

0          2016
1          2016
2          2016
3          2016
4          2016
           ...
1054939    2017
1054940    2017
1054941    2017
1054942    2017
1054943    2017
Name: date, Length: 1054944, dtype: int32

In [6]:
# Show the month
retail['date'].dt.month

0          1
1          1
2          1
3          1
4          1
          ..
1054939    8
1054940    8
1054941    8
1054942    8
1054943    8
Name: date, Length: 1054944, dtype: int32

In [7]:
# Show de day of the week
retail['date'].dt.dayofweek

0          4
1          4
2          4
3          4
4          4
          ..
1054939    1
1054940    1
1054941    1
1054942    1
1054943    1
Name: date, Length: 1054944, dtype: int32

In [8]:
# Show time
retail['date'].dt.time

0          00:00:00
1          00:00:00
2          00:00:00
3          00:00:00
4          00:00:00
             ...
1054939    00:00:00
1054940    00:00:00
1054941    00:00:00
1054942    00:00:00
1054943    00:00:00
Name: date, Length: 1054944, dtype: object

In [9]:
# Show the Hour
retail['date'].dt.hour

0          0
1          0
2          0
3          0
4          0
          ..
1054939    0
1054940    0
1054941    0
1054942    0
1054943    0
Name: date, Length: 1054944, dtype: int32

In [10]:
# Show the Minute
retail['date'].dt.minute

0          0
1          0
2          0
3          0
4          0
          ..
1054939    0
1054940    0
1054941    0
1054942    0
1054943    0
Name: date, Length: 1054944, dtype: int32

In [11]:
# Show the Seconds
retail['date'].dt.second

0          0
1          0
2          0
3          0
4          0
          ..
1054939    0
1054940    0
1054941    0
1054942    0
1054943    0
Name: date, Length: 1054944, dtype: int32

In [12]:
df = retail[['date']]
df

              date
0       2016-01-01
1       2016-01-01
2       2016-01-01
3       2016-01-01
4       2016-01-01
...            ...
1054939 2017-08-15
1054940 2017-08-15
1054941 2017-08-15
1054942 2017-08-15
1054943 2017-08-15

[1054944 rows x 1 columns]

In [13]:
df = df.assign(
    year = df['date'].dt.year,
    quarter = df['date'].dt.quarter,
    day_of_week = df['date'].dt.dayofweek,
)

df

              date  year  quarter  day_of_week
0       2016-01-01  2016        1            4
1       2016-01-01  2016        1            4
2       2016-01-01  2016        1            4
3       2016-01-01  2016        1            4
4       2016-01-01  2016        1            4
...            ...   ...      ...          ...
1054939 2017-08-15  2017        3            1
1054940 2017-08-15  2017        3            1
1054941 2017-08-15  2017        3            1
1054942 2017-08-15  2017        3            1
1054943 2017-08-15  2017        3            1

[1054944 rows x 4 columns]

---

## LABORATORY

In [14]:
retail.assign(
    year = retail['date'].dt.year,
    month = retail['date'].dt.month,
    day_of_week = retail['date'].dt.dayofweek,
    new_date = retail['date'].dt.date
)

,id,date,store_nbr,family,sales,onpromotion,year,month,day_of_week,new_date
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0,2016,1,4,2016-01-01
1,1945945,2016-01-01,1,BABY CARE,0.000,0,2016,1,4,2016-01-01
2,1945946,2016-01-01,1,BEAUTY,0.000,0,2016,1,4,2016-01-01
3,1945947,2016-01-01,1,BEVERAGES,0.000,0,2016,1,4,2016-01-01
4,1945948,2016-01-01,1,BOOKS,0.000,0,2016,1,4,2016-01-01
...,...,...,...,...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0,2017,8,1,2017-08-15
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1,2017,8,1,2017-08-15
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148,2017,8,1,2017-08-15
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8,2017,8,1,2017-08-15
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0,2017,8,1,2017-08-15