---

# TIME DELTAS & ARITHMETIC

---

>---
>**Time Deltas** represent the amount or time, or difference, between two datetimes.
>
>- A time delta is returned when subtracting two datetime values

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'order_date':['2021-04-04', '2021-05-23'],
                   'delivery_date':['2021-04-07', pd.NA]})

df = df.astype({'order_date':'datetime64[ns]', 'delivery_date':'datetime64[ns]'})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_date     2 non-null      datetime64[ns]
 1   delivery_date  1 non-null      datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 164.0 bytes

In [3]:
df['Ship_days'] = df.delivery_date - df.order_date # this operation create a `timedelta64[ns]`
df

  order_date delivery_date Ship_days
0 2021-04-04    2021-04-07    3 days
1 2021-05-23           NaT       NaT

In [4]:
df['shipping_days'] = (df.delivery_date - df.order_date).dt.days # This operation create a `float64`
df

  order_date delivery_date Ship_days  shipping_days
0 2021-04-04    2021-04-07    3 days            3.0
1 2021-05-23           NaT       NaT            NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_date     2 non-null      datetime64[ns]
 1   delivery_date  1 non-null      datetime64[ns]
 2   Ship_days      1 non-null      timedelta64[ns]
 3   shipping_days  1 non-null      float64
dtypes: datetime64[ns](2), float64(1), timedelta64[ns](1)
memory usage: 196.0 bytes

<br><br>

>---
>The `.to_timedelta()` method lets you use **frequencies** to return timedelta values
>

| **FREQUENCY** | **UNIT** |
|:---:|:---|
| `"W"` | Week |
| `"D"` | Day |
| `"h"` | Hour |
| `"min"` | Minute |
| `"s"` | Second |

In [6]:
pd.to_timedelta(5, unit='W')

Timedelta('35 days 00:00:00')

In [7]:
pd.to_timedelta(5, unit='D')

Timedelta('5 days 00:00:00')

In [8]:
pd.to_timedelta(5, unit='h')

Timedelta('0 days 05:00:00')

In [9]:
pd.to_timedelta(5, unit='min')

Timedelta('0 days 00:05:00')

In [10]:
pd.to_timedelta(5, unit='s')

Timedelta('0 days 00:00:05')

In [11]:
pd.to_timedelta(5, unit='Y')

ValueError: Units 'M', 'Y', and 'y' are no longer supported, as they do not represent unambiguous timedelta values durations.

>---
>Because months, quarters, and years have differing lengths, they are sometimes known as "anchored" frequencies, since they are anchored (*anclado*) to the end of calendar periods.
>
>They can't be used in time delta arithmetic, but are useful for things like resampling.
>

| **FREQUENCY** | **UNIT** |
|:---:|:---|
|`"M"` | Month end |
|`"Q"` | Quarter end |
|`"Y"` | Year end |

In [12]:
df

  order_date delivery_date Ship_days  shipping_days
0 2021-04-04    2021-04-07    3 days            3.0
1 2021-05-23           NaT       NaT            NaN

In [13]:
# Adding 1 day to "order_date"
df.order_date + pd.to_timedelta(1, unit="D")

0   2021-04-05
1   2021-05-24
Name: order_date, dtype: datetime64[ns]

In [14]:
# Adding 2 weeks to "order_date"
df.order_date + pd.to_timedelta(2, unit="W")

0   2021-04-18
1   2021-06-06
Name: order_date, dtype: datetime64[ns]

<br><br>

---

## LABORATORY

In [15]:
retail = pd.read_parquet('../Data/retail_2016_2017.parquet')
retail.head(3)

        id       date  store_nbr      family  sales  onpromotion
0  1945944 2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945 2016-01-01          1   BABY CARE    0.0            0
2  1945946 2016-01-01          1      BEAUTY    0.0            0

In [16]:
retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  datetime64[ns]
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  object
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 48.3+ MB

---

In [17]:
retail = retail.assign(
    birthday=pd.to_datetime('1950-01-01') # This columns is created as datetime64[ns]
)

retail.head(3)

        id       date  store_nbr      family  sales  onpromotion   birthday
0  1945944 2016-01-01          1  AUTOMOTIVE    0.0            0 1950-01-01
1  1945945 2016-01-01          1   BABY CARE    0.0            0 1950-01-01
2  1945946 2016-01-01          1      BEAUTY    0.0            0 1950-01-01

In [18]:
retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 7 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  datetime64[ns]
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  object
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
 6   birthday     1054944 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(3), object(1)
memory usage: 56.3+ MB

In [19]:
retail = retail.assign(
    age_in_days = retail.date - retail.birthday,
    age_in_days_num = (retail.date - retail.birthday).dt.days,
    age_in_years = (retail.date - retail.birthday).dt.days / 365.25,
    retirement_date = (retail.date + pd.to_timedelta(365.25, unit='D') * 20)
)

retail

,id,date,store_nbr,family,sales,onpromotion,birthday,age_in_days,age_in_days_num,age_in_years,retirement_date
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0,1950-01-01,24106 days,24106,65.998631,2036-01-01
1,1945945,2016-01-01,1,BABY CARE,0.000,0,1950-01-01,24106 days,24106,65.998631,2036-01-01
2,1945946,2016-01-01,1,BEAUTY,0.000,0,1950-01-01,24106 days,24106,65.998631,2036-01-01
3,1945947,2016-01-01,1,BEVERAGES,0.000,0,1950-01-01,24106 days,24106,65.998631,2036-01-01
4,1945948,2016-01-01,1,BOOKS,0.000,0,1950-01-01,24106 days,24106,65.998631,2036-01-01
...,...,...,...,...,...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0,1950-01-01,24698 days,24698,67.619439,2037-08-15
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1,1950-01-01,24698 days,24698,67.619439,2037-08-15
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148,1950-01-01,24698 days,24698,67.619439,2037-08-15
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8,1950-01-01,24698 days,24698,67.619439,2037-08-15
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0,1950-01-01,24698 days,24698,67.619439,2037-08-15