---

# TIME SERIES INDICES

---

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'date':['2022-01-01', '2022-01-02', '2022-02-01', '2022-03-01', '2023-01-01', '2023-01-02'],
                   'sales':[10, 15, pd.NA, 20, 30, 35]})
df['date'] = pd.to_datetime(df['date'], errors='coerce', format='%Y-%m-%d')

print(df.info())
print('-'*75)

df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    6 non-null      datetime64[ns]
 1   sales   5 non-null      object
dtypes: datetime64[ns](1), object(1)
memory usage: 228.0+ bytes
None
---------------------------------------------------------------------------

        date sales
0 2022-01-01    10
1 2022-01-02    15
2 2022-02-01  <NA>
3 2022-03-01    20
4 2023-01-01    30
5 2023-01-02    35

In [3]:
df[df['date'].dt.year == 2023]

        date sales
4 2023-01-01    30
5 2023-01-02    35

<br>

>---
>Use **datetimes as the index** to allow for intuitive slicing of your DataFrame.
>
>- Like with integers, make sure your time index is sorted or you will get very odd results.

In [4]:
# configure the 'date' column as index
df = df.set_index('date', verify_integrity=True)
df

           sales
date
2022-01-01    10
2022-01-02    15
2022-02-01  <NA>
2022-03-01    20
2023-01-01    30
2023-01-02    35

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2022-01-01 to 2023-01-02
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   sales   5 non-null      object
dtypes: object(1)
memory usage: 96.0+ bytes

## Filtering a DateTime index

In [6]:
# When 'datetime' column is the index the filtering task is easier
df.loc['2023']

           sales
date
2023-01-01    30
2023-01-02    35

In [7]:
# filtering year 2022
df.loc['2022']

           sales
date
2022-01-01    10
2022-01-02    15
2022-02-01  <NA>
2022-03-01    20

In [8]:
# filtering years 2022 and 2023
df.loc['2022':'2023']

           sales
date
2022-01-01    10
2022-01-02    15
2022-02-01  <NA>
2022-03-01    20
2023-01-01    30
2023-01-02    35

In [9]:
# filtering January and February from year 2022
df.loc['2022-01':'2022-02']

           sales
date
2022-01-01    10
2022-01-02    15
2022-02-01  <NA>

In [10]:
# filtering more specific dates YYYY-MM-DD
df.loc['2022-01-01':'2023-01-01']

           sales
date
2022-01-01    10
2022-01-02    15
2022-02-01  <NA>
2022-03-01    20
2023-01-01    30

---

## LABORATORY

In [11]:
retail = pd.read_parquet('../Data/retail_2016_2017.parquet')
retail.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  datetime64[ns]
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  object
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 100.4 MB

In [12]:
retail.head(3)

        id       date  store_nbr      family  sales  onpromotion
0  1945944 2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945 2016-01-01          1   BABY CARE    0.0            0
2  1945946 2016-01-01          1      BEAUTY    0.0            0

In [13]:
retail = retail.set_index('date')

retail

,id,store_nbr,family,sales,onpromotion
date,,,,,
2016-01-01,1945944,1,AUTOMOTIVE,0.000,0
2016-01-01,1945945,1,BABY CARE,0.000,0
2016-01-01,1945946,1,BEAUTY,0.000,0
2016-01-01,1945947,1,BEVERAGES,0.000,0
2016-01-01,1945948,1,BOOKS,0.000,0
...,...,...,...,...,...
2017-08-15,3000883,9,POULTRY,438.133,0
2017-08-15,3000884,9,PREPARED FOODS,154.553,1
2017-08-15,3000885,9,PRODUCE,2419.729,148
2017-08-15,3000886,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
2017-08-15,3000887,9,SEAFOOD,16.000,0

In [14]:
# filter all rows from 2017
retail.loc['2017']

,id,store_nbr,family,sales,onpromotion
date,,,,,
2017-01-01,2596374,1,AUTOMOTIVE,0.000,0
2017-01-01,2596375,1,BABY CARE,0.000,0
2017-01-01,2596376,1,BEAUTY,0.000,0
2017-01-01,2596377,1,BEVERAGES,0.000,0
2017-01-01,2596378,1,BOOKS,0.000,0
...,...,...,...,...,...
2017-08-15,3000883,9,POULTRY,438.133,0
2017-08-15,3000884,9,PREPARED FOODS,154.553,1
2017-08-15,3000885,9,PRODUCE,2419.729,148
2017-08-15,3000886,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
2017-08-15,3000887,9,SEAFOOD,16.000,0

In [15]:
# Filter all rows from August 2017
retail.loc['2017-08']

,id,store_nbr,family,sales,onpromotion
date,,,,,
2017-08-01,2974158,1,AUTOMOTIVE,5.000,0
2017-08-01,2974159,1,BABY CARE,0.000,0
2017-08-01,2974160,1,BEAUTY,4.000,0
2017-08-01,2974161,1,BEVERAGES,2627.000,26
2017-08-01,2974162,1,BOOKS,0.000,0
...,...,...,...,...,...
2017-08-15,3000883,9,POULTRY,438.133,0
2017-08-15,3000884,9,PREPARED FOODS,154.553,1
2017-08-15,3000885,9,PRODUCE,2419.729,148
2017-08-15,3000886,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
2017-08-15,3000887,9,SEAFOOD,16.000,0

In [16]:
# Filter all rows from August 1st of 2017
retail.loc['2017-08-01']

,id,store_nbr,family,sales,onpromotion
date,,,,,
2017-08-01,2974158,1,AUTOMOTIVE,5.000000,0
2017-08-01,2974159,1,BABY CARE,0.000000,0
2017-08-01,2974160,1,BEAUTY,4.000000,0
2017-08-01,2974161,1,BEVERAGES,2627.000000,26
2017-08-01,2974162,1,BOOKS,0.000000,0
...,...,...,...,...,...
2017-08-01,2975935,9,POULTRY,570.196000,0
2017-08-01,2975936,9,PREPARED FOODS,50.462997,0
2017-08-01,2975937,9,PRODUCE,2470.461000,151
2017-08-01,2975938,9,SCHOOL AND OFFICE SUPPLIES,203.000000,9
2017-08-01,2975939,9,SEAFOOD,19.316000,0

In [17]:
# Filter all rows from 2016 to August 1st 2017
retail.loc['2016':'2017-08-01']

,id,store_nbr,family,sales,onpromotion
date,,,,,
2016-01-01,1945944,1,AUTOMOTIVE,0.000000,0
2016-01-01,1945945,1,BABY CARE,0.000000,0
2016-01-01,1945946,1,BEAUTY,0.000000,0
2016-01-01,1945947,1,BEVERAGES,0.000000,0
2016-01-01,1945948,1,BOOKS,0.000000,0
...,...,...,...,...,...
2017-08-01,2975935,9,POULTRY,570.196000,0
2017-08-01,2975936,9,PREPARED FOODS,50.462997,0
2017-08-01,2975937,9,PRODUCE,2470.461000,151
2017-08-01,2975938,9,SCHOOL AND OFFICE SUPPLIES,203.000000,9
2017-08-01,2975939,9,SEAFOOD,19.316000,0

In [18]:
# Filter all rows from April 2016 to July 2nd 2017
retail.loc['2016-04':'2017-07-02']

,id,store_nbr,family,sales,onpromotion
date,,,,,
2016-04-01,2108106,1,AUTOMOTIVE,8.000,0
2016-04-01,2108107,1,BABY CARE,0.000,0
2016-04-01,2108108,1,BEAUTY,2.000,0
2016-04-01,2108109,1,BEVERAGES,2274.000,8
2016-04-01,2108110,1,BOOKS,0.000,0
...,...,...,...,...,...
2017-07-02,2922475,9,POULTRY,857.480,0
2017-07-02,2922476,9,PREPARED FOODS,168.582,1
2017-07-02,2922477,9,PRODUCE,2641.849,8
2017-07-02,2922478,9,SCHOOL AND OFFICE SUPPLIES,5.000,0
2017-07-02,2922479,9,SEAFOOD,33.926,0