---

# SHIFTING TIME SERIES

---

>---
>You can **shift a Series** by a specified number of rows using the `.shift()` method
>
>- This is helpful when working with time series to compare values against previous periods
>
>---

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.DataFrame({'sales':[10, 15, 15, 20, 30, 35]},
                 index=pd.date_range("2022-01-01", "2022-01-06"))

df

            sales
2022-01-01     10
2022-01-02     15
2022-01-03     15
2022-01-04     20
2022-01-05     30
2022-01-06     35

In [3]:
# Series shift forward one row by default, but you can specify any positive or negative number to shift the Series
df.shift()

            sales
2022-01-01    NaN
2022-01-02   10.0
2022-01-03   15.0
2022-01-04   15.0
2022-01-05   20.0
2022-01-06   30.0

In [4]:
df.shift(-1)

            sales
2022-01-01   15.0
2022-01-02   15.0
2022-01-03   20.0
2022-01-04   30.0
2022-01-05   35.0
2022-01-06    NaN

In [5]:
(df.shift(3, freq='infer'))

            sales
2022-01-04     10
2022-01-05     15
2022-01-06     15
2022-01-07     20
2022-01-08     30
2022-01-09     35

In [6]:
df.shift(3, freq='D')

            sales
2022-01-04     10
2022-01-05     15
2022-01-06     15
2022-01-07     20
2022-01-08     30
2022-01-09     35

>---
>In the following example we'll calculate period-over-period growth by leveraging a date shift:

$$\LARGE Growth_{(percent)} = \frac{\text{Current Period}}{\text{Previous Period}} -1$$

In [7]:
(df/df.shift(1)).sub(1).mul(100).round(2)

            sales
2022-01-01    NaN
2022-01-02  50.00
2022-01-03   0.00
2022-01-04  33.33
2022-01-05  50.00
2022-01-06  16.67

---

## LABORATORY

In [8]:
retail = pd.read_parquet('../Data/retail_2016_2017.parquet')
retail

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [9]:
df = retail.groupby('date').agg({'sales':'sum'}).round().iloc[1:10]
df

                sales
date
2016-01-02  1066677.0
2016-01-03  1226736.0
2016-01-04   955957.0
2016-01-05   835320.0
2016-01-06   821686.0
2016-01-07   653504.0
2016-01-08   713608.0
2016-01-09   989209.0
2016-01-10  1094694.0

In [10]:
df.assign(
    yesterday_sales = df.sales.shift(),
    difference_sales = df.sales - df.sales.shift(),
    ratio_sales = df.sales / df.sales.shift(),
         )

                sales  yesterday_sales  difference_sales  ratio_sales
date
2016-01-02  1066677.0              NaN               NaN          NaN
2016-01-03  1226736.0        1066677.0          160059.0     1.150054
2016-01-04   955957.0        1226736.0         -270779.0     0.779269
2016-01-05   835320.0         955957.0         -120637.0     0.873805
2016-01-06   821686.0         835320.0          -13634.0     0.983678
2016-01-07   653504.0         821686.0         -168182.0     0.795321
2016-01-08   713608.0         653504.0           60104.0     1.091972
2016-01-09   989209.0         713608.0          275601.0     1.386208
2016-01-10  1094694.0         989209.0          105485.0     1.106636