---

# PRO TIP: `.diff()`

---

>---
>The `.diff()` Method calculates the difference between the values in a Series and those same values shifted a specified number of periods
>
>- This is useful in measuring absolute changes over time
>  
>---

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'sales':[10, 15, 15, 20, 30, 35]},
                 index=pd.date_range("2022-01-01", "2022-01-06"))

df

            sales
2022-01-01     10
2022-01-02     15
2022-01-03     15
2022-01-04     20
2022-01-05     30
2022-01-06     35

In [3]:
df.diff()

            sales
2022-01-01    NaN
2022-01-02    5.0
2022-01-03    0.0
2022-01-04    5.0
2022-01-05   10.0
2022-01-06    5.0

In [5]:
# .diff() Method is equivalent to...
df - df.shift(1)

            sales
2022-01-01    NaN
2022-01-02    5.0
2022-01-03    0.0
2022-01-04    5.0
2022-01-05   10.0
2022-01-06    5.0

In [8]:
df

            sales
2022-01-01     10
2022-01-02     15
2022-01-03     15
2022-01-04     20
2022-01-05     30
2022-01-06     35

In [6]:
df.diff(2)

            sales
2022-01-01    NaN
2022-01-02    NaN
2022-01-03    5.0
2022-01-04    5.0
2022-01-05   15.0
2022-01-06   15.0

---

## LABORATORY

In [9]:
retail = pd.read_parquet('../Data/retail_2016_2017.parquet')
retail

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [11]:
df = retail.groupby('date').agg({'sales':'sum'}).round().iloc[1:10]
df

                sales
date
2016-01-02  1066677.0
2016-01-03  1226736.0
2016-01-04   955957.0
2016-01-05   835320.0
2016-01-06   821686.0
2016-01-07   653504.0
2016-01-08   713608.0
2016-01-09   989209.0
2016-01-10  1094694.0

In [19]:
df.assign(
    daily_change = df.sales.diff(),
    growth_percentage = ((df.sales.diff() / df.sales.shift())*100).round(2)
)

                sales  daily_change  growth_percentage
date
2016-01-02  1066677.0           NaN                NaN
2016-01-03  1226736.0      160059.0              15.01
2016-01-04   955957.0     -270779.0             -22.07
2016-01-05   835320.0     -120637.0             -12.62
2016-01-06   821686.0      -13634.0              -1.63
2016-01-07   653504.0     -168182.0             -20.47
2016-01-08   713608.0       60104.0               9.20
2016-01-09   989209.0      275601.0              38.62
2016-01-10  1094694.0      105485.0              10.66