---

# AGGREGATION & RESAMPLING

---

<br>

>---
>You can **aggregate time series** using the `.groupby()` Method, but depending on use case there are better methods.

<br>

In [1]:
import pandas as pd
import numpy as np

In [4]:
retail = pd.read_parquet('../Data/retail_2016_2017.parquet')
retail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  datetime64[ns]
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  object
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 48.3+ MB

In [5]:
retail.head(3)

        id       date  store_nbr      family  sales  onpromotion
0  1945944 2016-01-01          1  AUTOMOTIVE    0.0            0
1  1945945 2016-01-01          1   BABY CARE    0.0            0
2  1945946 2016-01-01          1      BEAUTY    0.0            0

In [6]:
df = retail[['date', 'sales']]
df

              date     sales
0       2016-01-01     0.000
1       2016-01-01     0.000
2       2016-01-01     0.000
3       2016-01-01     0.000
4       2016-01-01     0.000
...            ...       ...
1054939 2017-08-15   438.133
1054940 2017-08-15   154.553
1054941 2017-08-15  2419.729
1054942 2017-08-15   121.000
1054943 2017-08-15    16.000

[1054944 rows x 2 columns]

<br><br>

---

<br><br>

In [10]:
# This code sums all the sales per month, including all the years of the dataset
df.groupby(df.date.dt.month).agg({'sales':'sum'}).round()

           sales
date
1     50305965.0
2     45197521.0
3     49835799.0
4     51858334.0
5     51691280.0
6     47892041.0
7     50474150.0
8     34885737.0
9     22417448.0
10    24030390.0
11    24642640.0
12    29640288.0

In [13]:
# to filter per year we need to add the following...
df.groupby([df.date.dt.year, df.date.dt.month]).agg({'sales':'sum'}).round()

                sales
date date
2016 1     23977805.0
     2     21947409.0
     3     23131781.0
     4     25963025.0
     5     24779432.0
     6     22209219.0
     7     23462672.0
     8     22452414.0
     9     22417448.0
     10    24030390.0
     11    24642640.0
     12    29640288.0
2017 1     26328160.0
     2     23250112.0
     3     26704018.0
     4     25895308.0
     5     26911847.0
     6     25682822.0
     7     27011478.0
     8     12433323.0

<br><br>

>---
>**Resampling** is a special form of time series aggregation that modifies date indices and fills any gaps to create continuous date values.
>
>- Frequencie are used to define the granularityu (*you can use years, quarters, and months now.*)

In [21]:
df2 = df.set_index('date')

df2.resample('ME').sum().round()

                 sales
date
2016-01-31  23977805.0
2016-02-29  21947409.0
2016-03-31  23131781.0
2016-04-30  25963025.0
2016-05-31  24779432.0
2016-06-30  22209219.0
2016-07-31  23462672.0
2016-08-31  22452414.0
2016-09-30  22417448.0
2016-10-31  24030390.0
2016-11-30  24642640.0
2016-12-31  29640288.0
2017-01-31  26328160.0
2017-02-28  23250112.0
2017-03-31  26704018.0
2017-04-30  25895308.0
2017-05-31  26911847.0
2017-06-30  25682822.0
2017-07-31  27011478.0
2017-08-31  12433323.0

<br><br>

---

## LABORATORY

In [25]:
df_lab = df.copy()

df_lab = df_lab.set_index('date')

df_lab

               sales
date
2016-01-01     0.000
2016-01-01     0.000
2016-01-01     0.000
2016-01-01     0.000
2016-01-01     0.000
...              ...
2017-08-15   438.133
2017-08-15   154.553
2017-08-15  2419.729
2017-08-15   121.000
2017-08-15    16.000

[1054944 rows x 1 columns]

In [29]:
# Let's see the total sum of sales for each Quarter of the dataset
df_lab.resample('QE').sum().round()

                 sales
date
2016-03-31  69056995.0
2016-06-30  72951676.0
2016-09-30  68332535.0
2016-12-31  78313318.0
2017-03-31  76282290.0
2017-06-30  78489978.0
2017-09-30  39444801.0

In [31]:
df_lab.resample('YE').sum().round()

                  sales
date
2016-12-31  288654523.0
2017-12-31  194217068.0