---

# PREPROCESSING WITH `.read_csv()`

---

<br><br>

>---
>In this section we'll cover **Importing & Exporting Data** in Pandas, including reading in data from flat files and SQL tables, applying processing steps on import, and writing back out.
>
>- **Preprocessing Options**
>- **Flat Files**
>- **SQL Databases**
>- **Additional Formats**
>

<br><br>

>---
>**GOAL FOR THIS SECTION**
>
>- Apply data processing steps like converting data types, setting an index, and handling missing data during the import process.
>
>- Read & Write Data from different flat files and multiple Excel worksheets.
>
>- Connect to SQL Databases and create DataFrames from custom SQL queries.
>

<br><br>

---

## `.read_csv()` Revisited

>---
>
>The ***.read_csv()*** function only needs a file path to read in a file, but it also has many capabilities fro preprocessing the data using other arguments:
>

| **PARAMETER** | **=** | **SETTTING** | **DESCRIPTION** |
|---:|:---:|:---|:---|
| `file` | = | <span style='color:orange'>***path/name.csv***</span> | File path & name to read in (*can also be a URL*) |
| `sep` | = | <span style='color:orange'>***/***</span> | Character used to separate each column of values (*default is comma*) |
| `header` | = | <span style='color:orange'>***0*** | Row number to use as the column names (*default is "infer"*) |
| `names` | = | <span style='color:orange'>***["date", "sales"]*** | List of column names to override the existing ones |
| `index_col` | = | <span style='color:orange'>***"date"*** | Column name to be used as the DataFrame index |
| `usecols` | = | <span style='color:orange'>***["date", "sales"]***</span> | List of columns to keep in the DataFrame |
| `dtype` | = | <span style='color:orange'>***{"date":"datetime64[ns]", "sales":"Int32"}*** | Dictionary with column names and data types |
| `parse_dates` | = | <span style='color:orange'>***True*** | Converts date strings into datetimes when True |
| `infer_datetime_format` | = | <span style='color:orange'>***True*** | Makes parsing dates more efficient |
| `na_values` | = | <span style='color:orange'>***["-", "#N/A"]*** | Strings to recognize as **NaN values** |
| `nrows` | = | <span style='color:orange'>***100*** | Number of rows to read in |
| `skiprows` | = | <span style='color:orange'>***[0,2]*** | Line numbers to skip *(accepts lambda functions)* |
| `converters` | = | <span style='color:orange'>***{"sales":lambda x: f"${x}"}*** | Dictionary with column names and functions to apply |

---

>---
>Pandas will try to infer the **Column Names** in your file by default, but there are several options to override this behavior:

In [1]:
import pandas as pd
import numpy as np

In [2]:
# - The first row is used for the column headers by default.
# - A suffix of ".1" is added to avoid duplicated column names

df = pd.read_csv('../Data/monthly_sales.csv')
df

       Date Sales  Sales.1  Useless
0  10/10/21     5        1      NaN
1  10/11/21     .        2      NaN
2  10/12/21    15        3      NaN

In [3]:
# Specify "header=None" to keep all the rows in the file as data, and use integers as column names
pd.read_csv('../Data/monthly_sales.csv', header=None)

          0      1      2        3
0      Date  Sales  Sales  Useless
1  10/10/21      5      1      NaN
2  10/11/21      .      2      NaN
3  10/12/21     15      3      NaN

In [4]:
# Specify "header=0" and use the names argument to pass a list of desired column names
pd.read_csv('../Data/monthly_sales.csv', header=0)

       Date Sales  Sales.1  Useless
0  10/10/21     5        1      NaN
1  10/11/21     .        2      NaN
2  10/12/21    15        3      NaN

In [5]:
# We can set the column names before importing the CSV file...
cols = ['Date', 'grocety_sales', 'beer_sales', 'to_drop']

pd.read_csv('../Data/monthly_sales.csv', header=0, names=cols)

       Date grocety_sales  beer_sales  to_drop
0  10/10/21             5           1      NaN
1  10/11/21             .           2      NaN
2  10/12/21            15           3      NaN

<br><br>

---

## LABORATORY

In [6]:
oil = pd.read_csv('../Data/oil.csv')
oil

            date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [7]:
cols = ['Date', 'Oil_Price']

pd.read_csv('../Data/oil.csv', header=0, names=cols).reset_index()

      index        Date  Oil_Price
0         0  2013-01-01        NaN
1         1  2013-01-02      93.14
2         2  2013-01-03      92.97
3         3  2013-01-04      93.12
4         4  2013-01-07      93.20
...     ...         ...        ...
1213   1213  2017-08-25      47.65
1214   1214  2017-08-28      46.40
1215   1215  2017-08-29      46.46
1216   1216  2017-08-30      45.96
1217   1217  2017-08-31      47.26

[1218 rows x 3 columns]

In [8]:
pd.read_csv('../Data/oil_no_header.csv').head()

   2013-01-01  Unnamed: 1
0  2013-01-02       93.14
1  2013-01-03       92.97
2  2013-01-04       93.12
3  2013-01-07       93.20
4  2013-01-08       93.21

In [9]:
pd.read_csv('../Data/oil_no_header.csv', header=None).head()

            0      1
0  2013-01-01    NaN
1  2013-01-02  93.14
2  2013-01-03  92.97
3  2013-01-04  93.12
4  2013-01-07  93.20

In [10]:
pd.read_csv('../Data/oil_no_header.csv', header=None, names=cols).head()

         Date  Oil_Price
0  2013-01-01        NaN
1  2013-01-02      93.14
2  2013-01-03      92.97
3  2013-01-04      93.12
4  2013-01-07      93.20