---

# COLUMN SELECTION - SETTING AN INDEX

---

>---
>You can **set the index** for the DataFrame with the `index_col` argument
>
>- Pass a list of column names to create a multi-index DataFrame
>
>- Specify `parse_dates=True` to convert index date column to a datetime data type

In [1]:
import pandas as pd
import numpy as np

<br><br>

---

## 1. Setting the Index

In [2]:
# Setting "index_col='date'" will set date as a STRING
df = pd.read_csv('Data/oil.csv', index_col='date')
df

            dcoilwtico
date
2013-01-01         NaN
2013-01-02       93.14
2013-01-03       92.97
2013-01-04       93.12
2013-01-07       93.20
...                ...
2017-08-25       47.65
2017-08-28       46.40
2017-08-29       46.46
2017-08-30       45.96
2017-08-31       47.26

[1218 rows x 1 columns]

In [3]:
type(df.index)

pandas.core.indexes.base.Index

In [4]:
# If we want to filter by Year. We get an error
df.loc['2014']

KeyError: '2014'

In [5]:
# Now if we set "parse_date=True" and "index_col='date'" we do get an datetime64[ns] index
df = pd.read_csv('Data/oil.csv', index_col='date', parse_dates=True)
df

            dcoilwtico
date
2013-01-01         NaN
2013-01-02       93.14
2013-01-03       92.97
2013-01-04       93.12
2013-01-07       93.20
...                ...
2017-08-25       47.65
2017-08-28       46.40
2017-08-29       46.46
2017-08-30       45.96
2017-08-31       47.26

[1218 rows x 1 columns]

In [6]:
type(df.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [7]:
# Now if we want to filter by year again
df.loc['2014']

            dcoilwtico
date
2014-01-01         NaN
2014-01-02       95.14
2014-01-03       93.66
2014-01-06       93.12
2014-01-07       93.31
...                ...
2014-12-25         NaN
2014-12-26       54.59
2014-12-29       53.46
2014-12-30       54.14
2014-12-31       53.45

[261 rows x 1 columns]

<br><br>

---

## 2. Selecting Columns

<br>

>---
>You can **select the columns** to read in with the "use_cols" argument
>
>- This can save a lot of processing time and memory

In [9]:
# The original DataFrame has the following columns...
df = pd.read_csv('Data/retail_2016_2017.csv')
df

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [10]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  object
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  object
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 151.7 MB

In [12]:
# Now we'll work only with the columns "date" and "sales" the rest of the columns is noise for this case...
df = pd.read_csv('Data/retail_2016_2017.csv', usecols=['date', 'sales'])
df.head()

         date  sales
0  2016-01-01    0.0
1  2016-01-01    0.0
2  2016-01-01    0.0
3  2016-01-01    0.0
4  2016-01-01    0.0

In [13]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 2 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   date    1054944 non-null  object
 1   sales   1054944 non-null  float64
dtypes: float64(1), object(1)
memory usage: 67.4 MB

> If we contrasts the **Memory Usage** from the first and last import. We'll see that the **Memory Usage** has reduced more than the 50%.
>
> Which besides the noise of the useless columns is a great practice to do it while you import the CSV file.

<br><br>

---

## LABORATORY

In [14]:
cols = ['Date', 'Oil Price']

df = pd.read_csv('Data/oil.csv', 
                 names=cols, header=0, 
                 index_col='Date', parse_dates=True,
                )

df

            Oil Price
Date
2013-01-01        NaN
2013-01-02      93.14
2013-01-03      92.97
2013-01-04      93.12
2013-01-07      93.20
...               ...
2017-08-25      47.65
2017-08-28      46.40
2017-08-29      46.46
2017-08-30      45.96
2017-08-31      47.26

[1218 rows x 1 columns]

In [15]:
df.index.dtype

dtype('<M8[ns]')

In [16]:
type(df.index)

pandas.core.indexes.datetimes.DatetimeIndex