---

# ROW SELECTION & MISSING VALUES

---

<br><br>

>---
>You can **select the rows** to read in from the top with the `nrows` argument, and specify any rows to skip with `skiprows`

In [1]:
import pandas as pd
import numpy as np

In [2]:
# original Dataset...
df = pd.read_csv('Data/transactions.csv')
df

             date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83488 rows x 3 columns]

---

## Working with `nrows=`

In [3]:
# Fixed Dataset using "nrows"
# "nrows" is used for reading just pieces of large files
df = pd.read_csv('Data/transactions.csv', nrows=5)
df

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [4]:
len(df)

5

---

## Working with `skiprows=`

In [5]:
df = pd.read_csv('Data/transactions.csv', skiprows=[1, 3, 5])
df

             date  store_nbr  transactions
0      2013-01-02          1          2111
1      2013-01-02          3          3487
2      2013-01-02          5          1903
3      2013-01-02          6          2143
4      2013-01-02          7          1874
...           ...        ...           ...
83480  2017-08-15         50          2804
83481  2017-08-15         51          1573
83482  2017-08-15         52          2255
83483  2017-08-15         53           932
83484  2017-08-15         54           802

[83485 rows x 3 columns]

In [6]:
# if we set "skiprows=0" will remove the column names, so we'll need to configure it. 
# Or we'll have the first data-row as the "Column Name"...
# **REMEMBER THIS**
df = pd.read_csv('Data/transactions.csv', skiprows=[0, 2, 4])
df

       2013-01-01  25   770
0      2013-01-02   2  2358
1      2013-01-02   4  1922
2      2013-01-02   5  1903
3      2013-01-02   6  2143
4      2013-01-02   7  1874
...           ...  ..   ...
83480  2017-08-15  50  2804
83481  2017-08-15  51  1573
83482  2017-08-15  52  2255
83483  2017-08-15  53   932
83484  2017-08-15  54   802

[83485 rows x 3 columns]

In [7]:
# skip all the odd rows
df = pd.read_csv('Data/transactions.csv', skiprows=lambda x: x%2 == 1)
df

             date  store_nbr  transactions
0      2013-01-02          1          2111
1      2013-01-02          3          3487
2      2013-01-02          5          1903
3      2013-01-02          7          1874
4      2013-01-02          9          2940
...           ...        ...           ...
41739  2017-08-15         46          3197
41740  2017-08-15         48          2722
41741  2017-08-15         50          2804
41742  2017-08-15         52          2255
41743  2017-08-15         54           802

[41744 rows x 3 columns]

<br><br>

---

## Missing Values

<br>

>---
>You can specify strings (*or other values*) to treat as **missing values** with the `na_values` argument.
>
>- They are replaced with Numpy `NaN` values

In [8]:
# Original Dataset
df = pd.read_csv('Data/oil.csv')
df.head(15)

          date dcoilwtico
0   2013-01-01          .
1   2013-01-02      93.14
2   2013-01-03      92.97
3   2013-01-04      93.12
4   2013-01-07       93.2
5   2013-01-08    MISSING
6   2013-01-09      93.08
7   2013-01-10      93.81
8   2013-01-11    MISSING
9   2013-01-14      94.27
10  2013-01-15      93.26
11  2013-01-16          .
12  2013-01-17      95.49
13  2013-01-18      95.61
14  2013-01-21         ..

In [10]:
# Fixed Dataset with wrong values, converted into Missing Values
df = pd.read_csv('Data/oil.csv', na_values=['MISSING', '.', '..']) # "na_values" accepts also numbers
df.head(15)

          date  dcoilwtico
0   2013-01-01         NaN
1   2013-01-02       93.14
2   2013-01-03       92.97
3   2013-01-04       93.12
4   2013-01-07       93.20
5   2013-01-08         NaN
6   2013-01-09       93.08
7   2013-01-10       93.81
8   2013-01-11         NaN
9   2013-01-14       94.27
10  2013-01-15       93.26
11  2013-01-16         NaN
12  2013-01-17       95.49
13  2013-01-18       95.61
14  2013-01-21         NaN