---

# CONVERTERS - PRO TIP

---

>---
>You can apply functions to columns of data by using the `converters` argument.
>
>- Pass a dictionary with the column names as keys and the functions as values

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Data/oil.csv',
                names=['Date', 'Oil_Price'],
                header=0)
df.head(15)

          Date Oil_Price
0   2013-01-01         .
1   2013-01-02     93.14
2   2013-01-03     92.97
3   2013-01-04     93.12
4   2013-01-07      93.2
5   2013-01-08   MISSING
6   2013-01-09     93.08
7   2013-01-10     93.81
8   2013-01-11   MISSING
9   2013-01-14     94.27
10  2013-01-15     93.26
11  2013-01-16         .
12  2013-01-17     95.49
13  2013-01-18     95.61
14  2013-01-21        ..

In [3]:
# create a column "sales" that increases it's value by 1 each cell
add_col = list(range(1, len(df)+1))

df['Sales'] = add_col
df

            Date Oil_Price  Sales
0     2013-01-01         .      1
1     2013-01-02     93.14      2
2     2013-01-03     92.97      3
3     2013-01-04     93.12      4
4     2013-01-07      93.2      5
...          ...       ...    ...
1213  2017-08-25     47.65   1214
1214  2017-08-28      46.4   1215
1215  2017-08-29     46.46   1216
1216  2017-08-30     45.96   1217
1217  2017-08-31     47.26   1218

[1218 rows x 3 columns]

In [4]:
df.to_csv('Data/oil_expanded.csv', index=False)

<br>

---

In [5]:
df = pd.read_csv('Data/oil_expanded.csv')
df.head(15)

          Date Oil_Price  Sales
0   2013-01-01         .      1
1   2013-01-02     93.14      2
2   2013-01-03     92.97      3
3   2013-01-04     93.12      4
4   2013-01-07      93.2      5
5   2013-01-08   MISSING      6
6   2013-01-09     93.08      7
7   2013-01-10     93.81      8
8   2013-01-11   MISSING      9
9   2013-01-14     94.27     10
10  2013-01-15     93.26     11
11  2013-01-16         .     12
12  2013-01-17     95.49     13
13  2013-01-18     95.61     14
14  2013-01-21        ..     15

In [6]:
# Fills wrong values with Zero
missing = lambda x: x if x not in ['MISSING', '.', '..'] else 0

# Adds "$" char and 2 decimal zeros
currency = lambda x: f"${x}.00"

# Now we import again our DataFrame and fix the issues
df = pd.read_csv('Data/oil_expanded.csv', 
                 converters={'Oil_Price': missing,
                             'Sales': currency}
                )

df.head(15)

          Date Oil_Price   Sales
0   2013-01-01         0   $1.00
1   2013-01-02     93.14   $2.00
2   2013-01-03     92.97   $3.00
3   2013-01-04     93.12   $4.00
4   2013-01-07      93.2   $5.00
5   2013-01-08         0   $6.00
6   2013-01-09     93.08   $7.00
7   2013-01-10     93.81   $8.00
8   2013-01-11         0   $9.00
9   2013-01-14     94.27  $10.00
10  2013-01-15     93.26  $11.00
11  2013-01-16         0  $12.00
12  2013-01-17     95.49  $13.00
13  2013-01-18     95.61  $14.00
14  2013-01-21         0  $15.00

<br><br>

---

## LABORATORY

In [7]:
# Read original Dataset
oil = pd.read_csv('Data/oil.csv',
                  names=['Date', 'Oil_Price'], # Rename cols
                  header=0) # if you rename cols must set "header=0"

# Duplicate "Date" column
oil['Date_2'] = oil['Date'].copy()

# Create a new column with the index values
oil = oil.reset_index(drop=False)
oil = oil.astype({'Date':'datetime64[ns]',
                  'Date_2':'datetime64[ns]'})

oil['Oil_Price'] = pd.to_numeric(oil['Oil_Price'], errors='coerce')
# Save the final DataFrame for future work
oil.to_csv('Data/oil_double_date.csv', index=False)

oil.head()

   index       Date  Oil_Price     Date_2
0      0 2013-01-01        NaN 2013-01-01
1      1 2013-01-02      93.14 2013-01-02
2      2 2013-01-03      92.97 2013-01-03
3      3 2013-01-04      93.12 2013-01-04
4      4 2013-01-07      93.20 2013-01-07

In [8]:
oil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   index      1218 non-null   int64
 1   Date       1218 non-null   datetime64[ns]
 2   Oil_Price  1172 non-null   float64
 3   Date_2     1218 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(1)
memory usage: 38.2 KB

<br>

---

In [9]:
oil = pd.read_csv('Data/oil_double_date.csv',
                  parse_dates=['Date'],
                  index_col='Date',
                 )
oil.head()

            index  Oil_Price      Date_2
Date
2013-01-01      0        NaN  2013-01-01
2013-01-02      1      93.14  2013-01-02
2013-01-03      2      92.97  2013-01-03
2013-01-04      3      93.12  2013-01-04
2013-01-07      4      93.20  2013-01-07

In [10]:
oil.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1218 entries, 2013-01-01 to 2017-08-31
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   index      1218 non-null   int64
 1   Oil_Price  1172 non-null   float64
 2   Date_2     1218 non-null   object
dtypes: float64(1), int64(1), object(1)
memory usage: 38.1+ KB

In [11]:
oil.index.dtype

dtype('<M8[ns]')

In [13]:
string_slice = lambda x: int(x[0:4])

oil = pd.read_csv('Data/oil_double_date.csv',
                  parse_dates=['Date'],
                  index_col='Date',
                  converters={'Date_2':string_slice} # Returns the 4 digits of year
                 )
oil.head()

            index  Oil_Price  Date_2
Date
2013-01-01      0        NaN    2013
2013-01-02      1      93.14    2013
2013-01-03      2      92.97    2013
2013-01-04      3      93.12    2013
2013-01-07      4      93.20    2013