---

# ASSIGNMENT: IMPORTING DATA

---

In [1]:
import numpy as np
import pandas as pd

In [2]:
transactions = pd.read_csv('Data/transactions.csv', 
                          names=['Date', 'Store_Number', 'Transaction_Count'],
                          header=0,
                          parse_dates=['Date'],)
display(transactions.head())

transactions.info(memory_usage='deep')

        Date  Store_Number  Transaction_Count
0 2013-01-01            25                770
1 2013-01-02             1               2111
2 2013-01-02             2               2358
3 2013-01-02             3               3487
4 2013-01-02             4               1922

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               83488 non-null  datetime64[ns]
 1   Store_Number       83488 non-null  int64
 2   Transaction_Count  83488 non-null  int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 1.9 MB

In [3]:
transactions = (transactions.assign(
    target_pct = lambda x: x.Transaction_Count/2500,
    met_target = lambda x: x.target_pct >= 1,
    bonus_payable = lambda x: x.met_target * 100,
    month = transactions.Date.dt.month,
    day_of_week = transactions.Date.dt.day_of_week,)
)
transactions

,Date,Store_Number,Transaction_Count,target_pct,met_target,bonus_payable,month,day_of_week
0,2013-01-01,25,770,0.3080,False,0,1,1
1,2013-01-02,1,2111,0.8444,False,0,1,2
2,2013-01-02,2,2358,0.9432,False,0,1,2
3,2013-01-02,3,3487,1.3948,True,100,1,2
4,2013-01-02,4,1922,0.7688,False,0,1,2
...,...,...,...,...,...,...,...,...
83483,2017-08-15,50,2804,1.1216,True,100,8,1
83484,2017-08-15,51,1573,0.6292,False,0,8,1
83485,2017-08-15,52,2255,0.9020,False,0,8,1
83486,2017-08-15,53,932,0.3728,False,0,8,1
83487,2017-08-15,54,802,0.3208,False,0,8,1

In [4]:
transactions.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               83488 non-null  datetime64[ns]
 1   Store_Number       83488 non-null  int64
 2   Transaction_Count  83488 non-null  int64
 3   target_pct         83488 non-null  float64
 4   met_target         83488 non-null  bool
 5   bonus_payable      83488 non-null  int64
 6   month              83488 non-null  int32
 7   day_of_week        83488 non-null  int32
dtypes: bool(1), datetime64[ns](1), float64(1), int32(2), int64(3)
memory usage: 3.9 MB

<br><br>

---

<br><br>

In [5]:
# We will obtain the same results as the upper cell. But from the ".read_csv()" Function

transactions_assignment = pd.read_csv('Data/transactions.csv',
                                      names=['Date', 'Store_Number', 'Transaction_Count'], 
                                      header=0,
                                      skiprows=0,
                                      parse_dates=['Date'],
                                      dtype={'Store_Number':'Int8',
                                             'Transaction_Count':'Int16'}
                            ).assign(target_pct = lambda x: x.Transaction_Count/2500,
                                     met_target = lambda x: x.target_pct >= 1,
                                     bonus_payable = lambda x: x.met_target * 100,
                                     month = transactions.Date.dt.month,
                                     day_of_week = transactions.Date.dt.day_of_week,
                                     ).astype({'target_pct':'Float32',
                                               'month':'Int8',
                                               'day_of_week':'Int8'})
display(transactions_assignment)

transactions_assignment.info(memory_usage='deep')

,Date,Store_Number,Transaction_Count,target_pct,met_target,bonus_payable,month,day_of_week
0,2013-01-01,25,770,0.308,False,0,1,1
1,2013-01-02,1,2111,0.8444,False,0,1,2
2,2013-01-02,2,2358,0.9432,False,0,1,2
3,2013-01-02,3,3487,1.3948,True,100,1,2
4,2013-01-02,4,1922,0.7688,False,0,1,2
...,...,...,...,...,...,...,...,...
83483,2017-08-15,50,2804,1.1216,True,100,8,1
83484,2017-08-15,51,1573,0.6292,False,0,8,1
83485,2017-08-15,52,2255,0.902,False,0,8,1
83486,2017-08-15,53,932,0.3728,False,0,8,1
83487,2017-08-15,54,802,0.3208,False,0,8,1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               83488 non-null  datetime64[ns]
 1   Store_Number       83488 non-null  Int8
 2   Transaction_Count  83488 non-null  Int16
 3   target_pct         83488 non-null  Float32
 4   met_target         83488 non-null  boolean
 5   bonus_payable      83488 non-null  Int64
 6   month              83488 non-null  Int8
 7   day_of_week        83488 non-null  Int8
dtypes: Float32(1), Int16(1), Int64(1), Int8(3), boolean(1), datetime64[ns](1)
memory usage: 2.6 MB