---

# PARSING DATES & DATA TYPES

---

>---
>Dates are read in as object data types by default, buy you can **parse dates** with the `parse_dates` argument to convert them to `datetime64[ns]`
>
>- Specifying `infer_datetime_format=True` will speed up the date parsing

In [1]:
import pandas as pd
import numpy as np

In [4]:
# First look of the dataset
oil = pd.read_csv('Data/oil_expanded.csv')
oil.head(15)

          Date Oil_Price  Sales
0   2013-01-01         .      1
1   2013-01-02     93.14      2
2   2013-01-03     92.97      3
3   2013-01-04     93.12      4
4   2013-01-07      93.2      5
5   2013-01-08   MISSING      6
6   2013-01-09     93.08      7
7   2013-01-10     93.81      8
8   2013-01-11   MISSING      9
9   2013-01-14     94.27     10
10  2013-01-15     93.26     11
11  2013-01-16         .     12
12  2013-01-17     95.49     13
13  2013-01-18     95.61     14
14  2013-01-21        ..     15

In [5]:
# Now it's time to parse dates
df = pd.read_csv('Data/oil_expanded.csv',
                 parse_dates=['Date'],
                 na_values=['MISSING', '.', '..'],
                )

df.head(15)

         Date  Oil_Price  Sales
0  2013-01-01        NaN      1
1  2013-01-02      93.14      2
2  2013-01-03      92.97      3
3  2013-01-04      93.12      4
4  2013-01-07      93.20      5
5  2013-01-08        NaN      6
6  2013-01-09      93.08      7
7  2013-01-10      93.81      8
8  2013-01-11        NaN      9
9  2013-01-14      94.27     10
10 2013-01-15      93.26     11
11 2013-01-16        NaN     12
12 2013-01-17      95.49     13
13 2013-01-18      95.61     14
14 2013-01-21        NaN     15

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1218 non-null   datetime64[ns]
 1   Oil_Price  1172 non-null   float64
 2   Sales      1218 non-null   int64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 28.7 KB

<br><br>

---

>---
>You can set the **data type** for each column with the `dtype` argument by passing in a dictionary with column names as keys and desired data types as values.
>
>- Get your data into its most efficient format from the start

In [7]:
# Now it's time to parse dates
df = pd.read_csv('Data/oil_expanded.csv',
                 parse_dates=['Date'],
                 na_values=['MISSING', '.', '..'],
                 dtype={'Oil_Price':'float32',
                        'Sales':'int16'
                       }
                )

display(df.head(15))

df.info()

         Date  Oil_Price  Sales
0  2013-01-01        NaN      1
1  2013-01-02  93.139999      2
2  2013-01-03  92.970001      3
3  2013-01-04  93.120003      4
4  2013-01-07  93.199997      5
5  2013-01-08        NaN      6
6  2013-01-09  93.080002      7
7  2013-01-10  93.809998      8
8  2013-01-11        NaN      9
9  2013-01-14  94.269997     10
10 2013-01-15  93.260002     11
11 2013-01-16        NaN     12
12 2013-01-17  95.489998     13
13 2013-01-18  95.610001     14
14 2013-01-21        NaN     15

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1218 non-null   datetime64[ns]
 1   Oil_Price  1172 non-null   float32
 2   Sales      1218 non-null   int16
dtypes: datetime64[ns](1), float32(1), int16(1)
memory usage: 16.8 KB