---

# IMPORTING FROM TEXT & EXCEL FILES

---

<br><br>

>---
>The `.read_csv()` function can also **read in `.txt` files**, and other types of flat files.
>
>- Simply use the `sep` argument to specify the delimiter
>
>- You can also read in `.tsv` (*tab separated values1*) files and URLs pointing to text files
>

In [1]:
import pandas as pd
import numpy as np

<br><br>

---

## Reading a TXT File

In [3]:
# Error while importing the dataframe
pd.read_csv('Data/tab_separated.txt')

      Date\tSales
0   2021-10-10\t5
1  2021-10-11\t10
2  2021-10-12\t15
3  2021-10-13\t20
4  2021-10-14\t25
5  2021-10-15\t30
6  2021-10-16\t35
7  2021-10-17\t40

In [5]:
# The correct way to import this dataset is this...
pd.read_csv('Data/tab_separated.txt', sep='\t')

         Date  Sales
0  2021-10-10      5
1  2021-10-11     10
2  2021-10-12     15
3  2021-10-13     20
4  2021-10-14     25
5  2021-10-15     30
6  2021-10-16     35
7  2021-10-17     40

<br><br>

---

## Reading an EXCEL File

>---
>The `.read_excel()` function is used to **read in Excel files** in Pandas
>
>- You can specify worksheets by passing the sheet name or position to the `sheet_name` argument

In [7]:
# Leer el primer sheet (Sheet 1)
df1 = pd.read_excel('Data/monthly_sales.xlsx', sheet_name=0)

# Leer el segundo sheet (Sheet 2) - 0-indexed
df2 = pd.read_excel('Data/monthly_sales.xlsx', sheet_name=1)

display(df1)

df2

         Date  Sales
0  2021-10-10      5
1  2021-10-11     10
2  2021-10-12     15
3  2021-10-13     20
4  2021-10-14     25
5  2021-10-15     30
6  2021-10-16     35
7  2021-10-17     40

         Date  Sales
0  2021-11-10    105
1  2021-11-11    110
2  2021-11-12    115
3  2021-11-13    120
4  2021-11-14    125
5  2021-11-15    130
6  2021-11-16    135
7  2021-11-17    140

In [9]:
# O acceder por nombre
df1 = pd.read_excel('Data/monthly_sales.xlsx', sheet_name='Sheet 1')
df2 = pd.read_excel('Data/monthly_sales.xlsx', sheet_name='Sheet 2')

display(df1)

df2

         Date  Sales
0  2021-10-10      5
1  2021-10-11     10
2  2021-10-12     15
3  2021-10-13     20
4  2021-10-14     25
5  2021-10-15     30
6  2021-10-16     35
7  2021-10-17     40

         Date  Sales
0  2021-11-10    105
1  2021-11-11    110
2  2021-11-12    115
3  2021-11-13    120
4  2021-11-14    125
5  2021-11-15    130
6  2021-11-16    135
7  2021-11-17    140

In [11]:
# Leer TODOS los sheets como diccionario
all_sheets = pd.read_excel('Data/monthly_sales.xlsx', sheet_name=None)
# all_sheets = {'Sheet 1': DataFrame, 'Sheet 2': DataFrame}

all_sheets

{'Sheet 1':          Date  Sales
 0  2021-10-10      5
 1  2021-10-11     10
 2  2021-10-12     15
 3  2021-10-13     20
 4  2021-10-14     25
 5  2021-10-15     30
 6  2021-10-16     35
 7  2021-10-17     40,
 'Sheet 2':          Date  Sales
 0  2021-11-10    105
 1  2021-11-11    110
 2  2021-11-12    115
 3  2021-11-13    120
 4  2021-11-14    125
 5  2021-11-15    130
 6  2021-11-16    135
 7  2021-11-17    140}

<br><br>

>---
>You can use Pandas' `.concat()` function to **append data from multiple sheets

In [13]:
all_sheets = pd.concat(
    pd.read_excel('Data/monthly_sales.xlsx', sheet_name=None), 
    ignore_index=True
)

all_sheets

          Date  Sales
0   2021-10-10      5
1   2021-10-11     10
2   2021-10-12     15
3   2021-10-13     20
4   2021-10-14     25
5   2021-10-15     30
6   2021-10-16     35
7   2021-10-17     40
8   2021-11-10    105
9   2021-11-11    110
10  2021-11-12    115
11  2021-11-13    120
12  2021-11-14    125
13  2021-11-15    130
14  2021-11-16    135
15  2021-11-17    140


>- `sheet_name=None` makes pandas read every sheet and store them as a dictionary, which is appended using `.concat()`.
>
>- `ignore_index=True` makes sure each row has a unique index.

---

<br><br>